import type { HelpArticle } from "../types";

/** Concepts, project reports, lifecycle exceptions, setup & limits. */
export const CONCEPTS_REPORTS_ARTICLES: HelpArticle[] = [
  {
    slug: "afectaciones-comprometido-devengado-pagado",
    title: "Comprometido, devengado y pagado",
    summary:
      "No hay menú «Afectaciones»: cada operación imputa una capa de costo en EDT y costos. No sumes OC + factura.",
    intents: ["afectaciones", "edt-costos"],
    modules: ["presupuesto", "compras", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Compras", "Finanzas", "OWNER"],
    where: { menu: "Planificación → EDT y costos (tablero de capas)" },
    hrefs: [
      { kind: "project", suffix: "/control-costos", label: "EDT y costos" },
      { kind: "project", suffix: "/reportes/presupuesto-vs-real", label: "Presupuesto vs real" },
    ],
    steps: [
      "Confirmar OC (o activar subcontrato) → capa Comprometido.",
      "Emitir factura de proveedor → Devengado + CxP (y asiento DRAFT contable).",
      "Pagar la CxP → Pagado + egreso de caja.",
      "Certificar al cliente → Avance certificado (otra dimensión; no es costo de compra).",
      "Miralo por partida en Planificación → EDT y costos. Exposición ≈ devengado + comprometido abierto.",
    ],
    effects: [
      "El tablero de control de costos refleja las capas por partida hoja.",
      "Al anular el documento origen se revierten las capas según el flujo del documento.",
    ],
    pitfalls: [
      "No sumes OC + factura como «costo total» (doble conteo).",
      "Aprobar una OC sola no compromete: hay que Confirmar al proveedor.",
    ],
    relatedSlugs: [
      "leer-edt-y-costos",
      "orden-de-compra-y-afectar-edt",
      "presupuesto-vs-real",
      "circuito-comprar-material-hasta-pagarlo",
    ],
    keywords: [
      "afectaciones",
      "afectar edt",
      "comprometido",
      "devengado",
      "pagado",
      "exposicion",
      "capas de costo",
      "que es comprometido",
    ],
    guideRef: "§0.2 · §16 · §13.1",
  },
  {
    slug: "cuatro-dimensiones-de-avance",
    title: "Cuatro dimensiones de avance (no confundir)",
    summary:
      "En el cronograma: Real, plan (tiempo), cantidades y certificado. Cada una se mueve desde un módulo distinto.",
    intents: ["dimensiones-avance", "cronograma"],
    modules: ["cronograma", "libro-obra", "certificaciones"],
    level: "project",
    typicalRoles: ["PM", "Capataz"],
    where: { menu: "Planificación → Cronograma (detalle / Gantt / tabla)" },
    hrefs: [
      { kind: "project", suffix: "/cronograma", label: "Cronograma" },
      { kind: "project", suffix: "/libro-obra", label: "Libro de obra" },
      { kind: "project", suffix: "/certificaciones", label: "Certificaciones" },
    ],
    steps: [
      "Abrí Planificación → Cronograma. En detalle/tabla/Gantt ves Real / plan t. / cant. / cert.",
      "Real: lo mueve el libro de obra aprobado (o el PM con «Avance real %»).",
      "Plan (tiempo): automático según fechas vs hoy.",
      "Cantidades: libro de obra vs presupuesto.",
      "Certificado: solo el módulo Certificaciones (lectura en cronograma).",
      "En el Gantt: relleno oscuro = Real; franja ámbar = Cert.",
    ],
    pitfalls: [
      "No uses el % del Gantt como si fuera lo certificado al cliente.",
      "Sin partida EDT vinculada a la tarea no hay sync Real ni métricas de costo/cert.",
    ],
    relatedSlugs: [
      "importar-cronograma",
      "cargar-libro-de-obra",
      "emitir-y-aprobar-certificacion",
      "leer-edt-y-costos",
    ],
    keywords: [
      "avance",
      "dimensiones de avance",
      "real vs certificado",
      "gantt",
      "plan tiempo",
      "cantidades",
      "certificado",
      "confundir avance",
    ],
    guideRef: "§7.1",
  },
  {
    slug: "crear-adenda-de-presupuesto",
    title: "Crear una adenda / fase de presupuesto",
    summary:
      "Cambio contractual operativo = nuevo presupuesto hijo (Crear adenda / fase). No hay entidad formal Contract/CO.",
    intents: ["adenda-presupuesto", "presupuesto-edt-apu"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["PM", "OWNER / ADMIN"],
    where: { menu: "Planificación → Presupuestos → detalle → Crear adenda / fase" },
    hrefs: [
      { kind: "project", suffix: "/presupuestos", label: "Presupuestos" },
    ],
    steps: [
      "Abrí el presupuesto APPROVED/CLOSED que será padre.",
      "Pulsá Crear adenda / fase (alta con parentBudgetId).",
      "Se prellenan % económicos (GG, financiero, utilidad, IVA) y moneda del padre; editables.",
      "Armá la EDT/APU de la adenda (no se copia sola la EDT del padre).",
      "Enviá a revisión y aprobá cuando corresponda. El rótulo v{n} es presentación, no versionado contractual.",
    ],
    pitfalls: [
      "Contratos, adendas y órdenes de cambio formales aún no existen como módulo (§19).",
      "Seguí teniendo un solo presupuesto APPROVED «activo» según las reglas de la obra.",
    ],
    relatedSlugs: [
      "armar-presupuesto-edt-apu",
      "aprobar-el-presupuesto",
      "limitaciones-actuales-de-bloqer",
    ],
    keywords: [
      "adenda",
      "adenda presupuesto",
      "fase",
      "cambio contractual",
      "orden de cambio",
      "parent budget",
      "crear adenda",
    ],
    guideRef: "§6.3 · §19",
  },
  {
    slug: "anular-devolver-cancelar-documentos",
    title: "Anular, devolver o cancelar un documento",
    summary:
      "Cada documento tiene su acción: Devolver (OC/presupuesto), Anular (OC, facturas, SC…) o Cancelar certificación.",
    intents: ["anular-documentos"],
    modules: ["compras", "finanzas", "certificaciones", "presupuesto"],
    level: "both",
    typicalRoles: ["Compras", "PM", "Finanzas", "OWNER / ADMIN"],
    where: { menu: "Detalle del documento → Anular / Devolver / Cancelar" },
    hrefs: [
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "project", suffix: "/certificaciones", label: "Certificaciones" },
      { kind: "company", path: "/finanzas/facturas-proveedor", label: "Facturas de proveedor" },
    ],
    steps: [
      "OC en aprobación: Devolver a borrador (motivo). OC confirmada/aprobada: Anular según estado permitido.",
      "Solicitud de compra: Anular desde el detalle.",
      "Factura de venta (obra) o factura de proveedor: Anular en el detalle (obra o Finanzas).",
      "Certificación al cliente: Cancelar certificación (no dice «Anular»).",
      "Certificación de subcontrato / recepción / parte de obra: Anular en su detalle.",
      "Si el documento ya generó asiento POSTED sin reverso, o un movimiento Conciliado, el sistema puede bloquear la anulación hasta revertir/desemparejar.",
    ],
    pitfalls: [
      "Devolver ≠ Anular: devolver vuelve a borrador; anular cierra el ciclo.",
      "Mes cerrado (Contabilidad → Cierres) bloquea mutaciones con fecha en ese período.",
    ],
    relatedSlugs: [
      "orden-de-compra-y-afectar-edt",
      "por-que-un-pago-se-bloquea",
      "cerrar-el-mes",
      "contabilizar-asientos",
      "errores-operativos-frecuentes",
    ],
    keywords: [
      "anular",
      "devolver",
      "cancelar",
      "devolver a borrador",
      "cancelar certificacion",
      "anular oc",
      "anular factura",
      "deshacer",
    ],
    guideRef: "§9.2 · §11 · §12 · §8",
  },
  {
    slug: "hub-reportes-de-obra",
    title: "Dónde ver los reportes de la obra",
    summary:
      "Planificación → Reportes: hub con rentabilidad, presupuesto vs real, compras, caja, certificaciones y más.",
    intents: ["reportes-obra", "exportar-reportes"],
    modules: ["presupuesto", "finanzas", "compras"],
    level: "project",
    typicalRoles: ["PM", "Finanzas", "OWNER / ADMIN"],
    permissionHint: "Cada card aparece según módulos y permisos del rol.",
    where: { menu: "Planificación → Reportes" },
    hrefs: [
      { kind: "project", suffix: "/reportes", label: "Reportes del proyecto" },
      { kind: "project", suffix: "/reportes/programados", label: "Envíos programados" },
    ],
    steps: [
      "Planificación → Reportes (título: Reportes del proyecto).",
      "Elegí la card: Rentabilidad, Presupuesto vs real, EDT y costos, Compras y proveedores, Materiales, Subcontratos, Certificaciones, Ingresos vs gastos, Caja y proyección, Flujo de caja, aging CxC/CxP.",
      "Dentro de cada reporte usá Exportar → CSV o PDF (o Exportar PDF si solo hay PDF).",
      "Si tenés permiso: Envíos programados por email desde el hub o /reportes/programados.",
    ],
    pitfalls: [
      "Si no ves cards: faltan módulos (presupuestos, AR/AP…) o permisos del rol.",
      "Aging CxC/CxP del hub abre las pantallas operativas de cuentas, no un PDF aparte.",
    ],
    relatedSlugs: [
      "presupuesto-vs-real",
      "ver-rentabilidad-de-obra",
      "exportar-reportes-csv-pdf",
      "leer-edt-y-costos",
    ],
    keywords: [
      "reportes",
      "reportes del proyecto",
      "hub reportes",
      "donde veo reportes",
      "exportar",
      "pdf",
      "csv",
      "envios programados",
    ],
    guideRef: "§13.2",
  },
  {
    slug: "presupuesto-vs-real",
    title: "Comparar presupuesto vs real",
    summary:
      "Reporte de desvíos presupuesto baseline vs ejecución. Complementa el tablero EDT y costos.",
    intents: ["presupuesto-vs-real", "edt-costos", "exportar-reportes"],
    modules: ["presupuesto", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas", "OWNER"],
    where: { menu: "Planificación → Reportes → Presupuesto vs real" },
    hrefs: [
      { kind: "project", suffix: "/reportes/presupuesto-vs-real", label: "Presupuesto vs real" },
      { kind: "project", suffix: "/control-costos", label: "EDT y costos" },
    ],
    steps: [
      "Planificación → Reportes → Presupuesto vs real (también card Composición presupuesto).",
      "Arriba: 5 indicadores (presupuesto, exposición, certificado, variación, consumo).",
      "Abajo: gráfico de composición APU y la tabla de varianza por partida.",
      "Para el día a día por capas (comprometido/devengado/pagado) usá EDT y costos.",
      "Exportá con Exportar → CSV o PDF.",
    ],
    pitfalls: [
      "Presupuesto vs real y EDT y costos se miran juntos: uno es reporte de varianza; el otro es tablero operativo de afectaciones.",
    ],
    relatedSlugs: [
      "hub-reportes-de-obra",
      "leer-edt-y-costos",
      "afectaciones-comprometido-devengado-pagado",
      "ver-rentabilidad-de-obra",
      "exportar-reportes-csv-pdf",
    ],
    keywords: [
      "presupuesto vs real",
      "presupuestado vs real",
      "desvio",
      "varianza",
      "comparar presupuesto",
      "composicion presupuesto",
      "baseline",
    ],
    guideRef: "§13.1 · §13.2",
  },
  {
    slug: "ver-rentabilidad-de-obra",
    title: "Ver la rentabilidad de la obra",
    summary:
      "Margen bruto por capas de costo; margen neto (GG imputados) visible a OWNER/ADMIN.",
    intents: ["rentabilidad", "exportar-reportes"],
    modules: ["presupuesto", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "OWNER / ADMIN", "Finanzas"],
    where: { menu: "Planificación → Reportes → Rentabilidad" },
    hrefs: [
      { kind: "project", suffix: "/reportes/rentabilidad", label: "Rentabilidad del proyecto" },
      { kind: "company", path: "/finanzas/gastos-generales", label: "Gastos generales" },
    ],
    steps: [
      "Planificación → Reportes → Rentabilidad (también desde el KPI del resumen de obra).",
      "Revisá margen bruto según capas de costo.",
      "OWNER/ADMIN: margen neto si hay gastos generales imputados a la obra.",
      "Exportá CSV/PDF con Exportar.",
      "Para prorratear overhead: Finanzas → Gastos generales (empresa).",
    ],
    pitfalls: [
      "Sin imputar GG no esperes margen neto completo.",
      "Rentabilidad de obra ≠ reportes contables de empresa (libro diario / EERR).",
    ],
    relatedSlugs: [
      "hub-reportes-de-obra",
      "imputar-gastos-generales",
      "presupuesto-vs-real",
      "exportar-reportes-csv-pdf",
    ],
    keywords: [
      "rentabilidad",
      "margen",
      "margen bruto",
      "margen neto",
      "ganancia obra",
      "profitability",
      "overhead",
    ],
    guideRef: "§13.2 · §14",
  },
  {
    slug: "exportar-reportes-csv-pdf",
    title: "Exportar reportes a PDF o CSV",
    summary:
      "En pantallas de reporte: botón Exportar (CSV + PDF) o Exportar PDF. Misma idea en contabilidad, tesorería y registro.",
    intents: ["exportar-reportes"],
    modules: ["presupuesto", "contabilidad", "tesoreria", "finanzas", "configuracion"],
    level: "both",
    typicalRoles: ["PM", "Finanzas", "Contabilidad", "OWNER / ADMIN"],
    where: { menu: "Dentro del reporte → Exportar / Exportar PDF" },
    hrefs: [
      { kind: "project", suffix: "/reportes", label: "Reportes del proyecto" },
      { kind: "company", path: "/contabilidad/libro-diario", label: "Libro diario" },
      { kind: "company", path: "/configuracion/registro", label: "Registro de actividad" },
    ],
    steps: [
      "Abrí el reporte (obra: Reportes → card; empresa: Contabilidad / Tesorería / Finanzas / Inventario).",
      "Pulsá Exportar y elegí CSV o PDF. Si solo hay PDF, el botón dice Exportar PDF.",
      "En sumas y saldos / diario / ESP / EERR también hay XLSX cuando la pantalla lo ofrece.",
      "Presupuesto EDT: export desde el detalle del presupuesto.",
      "Materiales → Varianza ($): Exportar (CSV/PDF) en la misma fila que Operativo / Varianza.",
      "Libro de obra (parte): Exportar PDF del parte.",
      "Registro de actividad: CSV/PDF en zona horaria de la empresa.",
    ],
    pitfalls: [
      "Mientras dice «Generando…» esperá; no reintentar mil veces.",
      "Los libros contables solo incluyen asientos Contabilizados (POSTED).",
    ],
    relatedSlugs: [
      "hub-reportes-de-obra",
      "leer-reportes-contables",
      "ver-registro-de-actividad",
      "ver-rentabilidad-de-obra",
      "presupuesto-vs-real",
    ],
    keywords: [
      "exportar",
      "exportar pdf",
      "exportar csv",
      "pdf",
      "csv",
      "xlsx",
      "descargar reporte",
      "imprimir reporte",
      "bajar pdf",
    ],
    guideRef: "§13.2 · §15.1 · §1.3a",
  },
  {
    slug: "montos-y-decimales",
    title: "Montos y decimales (regla diaria)",
    summary:
      "Dinero a 2 decimales; FX a 6; cantidades y % a 4. Al pagar/cobrar usá el saldo que muestra el sistema.",
    intents: ["montos-decimales"],
    modules: ["finanzas", "tesoreria", "general"],
    level: "both",
    typicalRoles: ["Administración", "Finanzas", "Compras", "PM"],
    where: { menu: "Cualquier formulario de monto / pago / cobro" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "project", suffix: "/cuentas-por-pagar", label: "Cuentas por pagar" },
    ],
    steps: [
      "Dinero (totales, saldos, caja): siempre 2 decimales (ej. 1.234,56), redondeo comercial half-up.",
      "Tipo de cambio: hasta 6 decimales.",
      "Cantidades y % (IVA, descuento comercial, etc.): hasta 4 decimales.",
      "Al pagar o cobrar el total: click en el saldo pendiente o dejá el default; no reescribas un redondeo distinto.",
      "Sin fondos suficientes en la cuenta, el pago se rechaza.",
    ],
    pitfalls: [
      "Reescribir el monto «a ojo» genera residual o rechazo del servidor.",
      "Cobros/pagos/transferencias exigen la misma moneda de la cuenta (sin FX automático).",
    ],
    relatedSlugs: [
      "pagar-una-cuenta-por-pagar",
      "cobrar-una-cxc-de-obra",
      "por-que-un-pago-se-bloquea",
      "errores-operativos-frecuentes",
      "descuento-porcentual-en-lineas",
    ],
    keywords: [
      "decimales",
      "2 decimales",
      "redondeo",
      "montos",
      "d-053",
      "saldo pendiente",
      "centavos",
    ],
    guideRef: "§4.1 · D-053",
  },
  {
    slug: "ver-registro-de-actividad",
    title: "Ver el registro de actividad",
    summary:
      "Auditoría de quién hizo qué: Configuración → Registro. Fechas en zona de la empresa.",
    intents: ["registro-actividad"],
    modules: ["configuracion"],
    level: "company",
    typicalRoles: ["OWNER / ADMIN"],
    permissionHint: "Solo OWNER/ADMIN (permiso de auditoría).",
    where: { menu: "Configuración → Registro" },
    hrefs: [{ kind: "company", path: "/configuracion/registro", label: "Registro de actividad" }],
    steps: [
      "Configuración → Registro.",
      "Filtrá / abrí el detalle: actor, entidad, acción y fecha.",
      "Las horas están en la zona horaria de la empresa (no UTC del servidor).",
      "Exportá CSV o PDF si necesitás respaldo (el CSV indica la zona en el encabezado).",
    ],
    relatedSlugs: [
      "configurar-empresa-logo-zona",
      "exportar-reportes-csv-pdf",
      "invitar-un-usuario",
    ],
    keywords: [
      "registro",
      "auditoria",
      "registro de actividad",
      "quien hizo que",
      "log",
      "historial",
    ],
    guideRef: "§1.3a",
  },
  {
    slug: "puesta-en-marcha-contable",
    title: "Puesta en marcha contable (una vez)",
    summary:
      "Plantilla AR → reglas → operar finanzas → Contabilizar borradores → reportes → cierre de mes.",
    intents: ["puesta-marcha-contable", "plan-cuentas", "contabilizar"],
    modules: ["contabilidad", "finanzas"],
    level: "company",
    typicalRoles: ["OWNER / ADMIN", "Contabilidad"],
    permissionHint: "Company finance + módulo Contabilidad habilitado.",
    where: { menu: "Contabilidad → Cuentas / Asientos / Cierres" },
    hrefs: [
      { kind: "company", path: "/contabilidad/cuentas", label: "Plan de cuentas" },
      { kind: "company", path: "/contabilidad/asientos", label: "Asientos" },
      { kind: "company", path: "/contabilidad/cierres", label: "Cierres" },
    ],
    steps: [
      "Contabilidad → Cuentas → Aplicar plantilla AR si el plan está vacío.",
      "Revisá Contabilidad → Reglas (mapeo evento → Debe/Haber).",
      "Operá facturas, cobros, pagos y transferencias con normalidad (generan DRAFT solos).",
      "Hub Contabilidad o Asientos: revisá borradores → Contabilizar (nunca auto-POST).",
      "Corré Libro diario / Sumas y saldos / Situación / Resultados (solo POSTED).",
      "Orden de mes: cobros/pagos OK → contabilizar → conciliar banco → Cerrar período.",
    ],
    pitfalls: [
      "Apareció el borrador ≠ está en los libros: hay que Contabilizar.",
      "Gerencial interno ≠ AFIP ni cierre de ejercicio GL.",
    ],
    relatedSlugs: [
      "aplicar-plantilla-plan-de-cuentas",
      "contabilizar-asientos",
      "leer-reportes-contables",
      "cerrar-el-mes",
      "conciliar-el-banco",
      "limitaciones-actuales-de-bloqer",
    ],
    keywords: [
      "puesta en marcha",
      "arrancar contabilidad",
      "primer asiento",
      "plantilla ar",
      "setup contable",
      "como empiezo contabilidad",
    ],
    guideRef: "§15.0 · §15.2 · §15.3",
  },
  {
    slug: "checklist-habitos-por-rol",
    title: "Checklist de hábitos por rol",
    summary:
      "Qué mirar cada día/semana según Dueño, PM, Capataz, Compras, Admin/Finanzas o Contabilidad.",
    intents: ["checklist-roles"],
    modules: ["general", "configuracion"],
    level: "both",
    typicalRoles: ["OWNER", "PM", "Capataz", "Compras", "Finanzas", "Contabilidad"],
    where: { menu: "Ayuda (esta ficha) · guía §18" },
    hrefs: [
      { kind: "company", path: "/ayuda", label: "Centro de ayuda" },
      { kind: "company", path: "/dashboard", label: "Inicio" },
    ],
    steps: [
      "Dueño: usuarios/roles, módulos, caja con apertura, plantilla contable, rentabilidad neta, alertas, cierre de mes.",
      "PM: obra ACTIVE, presupuesto APPROVED, APU bien modelado, cronograma, libro de obra, Materiales, certificaciones, EDT y costos semanal.",
      "Capataz: parte diario enviado; consumos con partida si aplica.",
      "Compras: política, Materiales/faltantes, SC→cotización→OC→confirmar→recepción→factura; verificar EDT y costos.",
      "Admin/Finanzas: facturas/cobranzas, CxP, sueldos/reintegros a Empleado, conciliación, aging.",
      "Contabilidad: borradores → Contabilizar → libros → pedir cierre de período.",
    ],
    pitfalls: [
      "Dar company finance a PM/Compras «para ver más» les abre hub/caja/GL de empresa (D-056).",
    ],
    relatedSlugs: [
      "que-ve-cada-rol",
      "errores-operativos-frecuentes",
      "hub-reportes-de-obra",
      "puesta-en-marcha-contable",
    ],
    keywords: [
      "checklist",
      "habitos",
      "por rol",
      "rutina",
      "que tengo que hacer",
      "dueño",
      "jefe de obra",
      "compras",
    ],
    guideRef: "§18",
  },
  {
    slug: "limitaciones-actuales-de-bloqer",
    title: "Limitaciones actuales de Bloqer",
    summary:
      "Qué aún no hace el producto (contratos formales, nómina, 2FA, API banco, AFIP, etc.) para no asumir de más.",
    intents: ["limitaciones"],
    modules: ["general", "configuracion"],
    level: "both",
    typicalRoles: ["OWNER / ADMIN", "PM", "Finanzas"],
    where: { menu: "Ayuda (esta ficha) · guía §19" },
    hrefs: [{ kind: "company", path: "/ayuda", label: "Centro de ayuda" }],
    steps: [
      "Contabilidad: DRAFT auto, Contabilizar manual; sin cierre de ejercicio GL ni AFIP.",
      "Conciliación: CSV/OFX sí; API directa al banco no.",
      "Contratos/CO formales no; adenda operativa = presupuesto hijo.",
      "Sin RFIs, 2FA, nómina/liquidación de haberes, valuación FIFO de stock.",
      "Multi-moneda: misma moneda por operación; sin consolidación FX.",
      "Anticipo a proveedor: sin CTA en UI. Documentos sin R2 = badge PLACEHOLDER.",
      "Roles fijos; sin techos «solo su proyecto» por membresía aún.",
    ],
    pitfalls: [
      "Estas limitaciones no impiden el uso productivo, pero evitan expectativas incorrectas.",
    ],
    relatedSlugs: [
      "crear-adenda-de-presupuesto",
      "pagar-un-sueldo",
      "puesta-en-marcha-contable",
      "conciliar-el-banco",
      "errores-operativos-frecuentes",
    ],
    keywords: [
      "limitaciones",
      "que no hace",
      "no implementado",
      "afip",
      "nomina",
      "2fa",
      "api banco",
      "contratos",
      "rfi",
    ],
    guideRef: "§19",
  },
];
