import type { HelpArticle } from "../types";

export const CONTROL_ARTICLES: HelpArticle[] = [
  {
    slug: "leer-edt-y-costos",
    title: "Leer EDT y costos",
    summary: "Tablero de afectaciones: Comprometido, Devengado, Pagado por partida.",
    intents: ["edt-costos"],
    modules: ["presupuesto", "compras", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas de obra", "OWNER"],
    where: { menu: "Planificación → EDT y costos" },
    hrefs: [{ kind: "project", suffix: "/control-costos", label: "EDT y costos" }],
    steps: [
      "Planificación → EDT y costos.",
      "Comprometido = OC confirmada / subcontrato (neto, sin IVA).",
      "Devengado = factura emitida.",
      "Pagado = egreso de caja aplicado.",
      "Usá Vista de columnas según lo que necesites: **Financiero** (solo $), **Cantidades** (qty + % avance libro + % recepción), **% Avance** (todas las capas + %) o **Compacto**.",
      "Arriba de la tabla ves dos gráficos lado a lado: **Composición del presupuesto** (torta APU planificada) y **Gasto por tipo** (barras Presup / Devengado / Exposición por MAT · LAB · EQP · SUB · OTHER).",
      "Filtro **Tipo de costo** en la barra: al elegir MAT / LAB / EQP / SUB / OTHER, la tabla muestra solo ese bucket por partida y los totales del proyecto se recalculan para ese tipo. El CSV / PDF respeta el filtro.",
      "En una partida hoja, el chevron a la izquierda del código abre el desglose por tipo de costo (solo cuando el filtro está en Todos los tipos).",
      "Tocá una fila (código o nombre, p. ej. 1.1 Replanteo de Obra) para abrir el detalle en un diálogo; ahí también está la sección Por tipo de costo.",
      "Desde el diálogo hay links a OC, facturas y pagos de esa partida.",
    ],
    pitfalls: [
      "No sumes OC + factura como costo total (doble conteo): mirá exposición esperada.",
      "Presupuesto vs real ya no es una pantalla aparte: vivía acá ([D-098]).",
      "**% recepción ≠ % avance libro**: recepción mide cobertura física de la compra (qty recibida / presup.); avance libro mide qty ejecutada en partes APPROVED. Si el capataz cargó 95% pero no hay OC recibida, % recepción queda en 0 y eso es correcto ([D-045]). Un parte solo enviado (SUBMITTED) no mueve % avance libro. La vista *Financiero* no muestra esas columnas: usá *Cantidades* o *% Avance*.",
      "Al elegir la partida en una OC / factura, el sistema pre-tipa la línea con la categoría dominante del APU (baño químico = EQP, excavación con retro = EQP, etc.). Podés cambiarla en el selector; si lo hacés a mano, no la pisamos cuando cambies la partida.",
      "**Mano de obra en factura de proveedor**: si contratás una cuadrilla externa o pagás un jornal como AP, tipá la línea como **LAB** — no hace falta que sea subcontrato. Subcontrato = módulo Subcontratos con certificación (SUB).",
    ],
    relatedSlugs: [
      "circuito-comprar-material-hasta-pagarlo",
      "tablero-materiales",
      "orden-de-compra-y-afectar-edt",
      "afectaciones-comprometido-devengado-pagado",
      "presupuesto-vs-real",
      "hub-reportes-de-obra",
    ],
    keywords: [
      "edt y costos",
      "control de costos",
      "comprometido",
      "devengado",
      "exposición",
      "presupuestado vs real",
      "detalle partida",
      "abrir partida",
      "vista de columnas",
      "porcentaje avance",
      "% recepción",
      "% avance libro",
      "cantidades",
      "composición presupuesto",
      "tipo de costo",
      "filtro tipo de costo",
      "gasto por tipo",
      "mano de obra",
      "mano de obra proveedor",
      "jornal",
      "materiales vs mano de obra",
      "MAT LAB EQP SUB",
      "expandir partida",
      "barras presupuesto real",
    ],
    guideRef: "§13 · §0.2 · §16 · [D-098] · [D-099]",
  },
  {
    slug: "aplicar-plantilla-plan-de-cuentas",
    title: "Aplicar plantilla de plan de cuentas",
    summary: "Si el plan está vacío, aplicá la plantilla AR antes de operar contabilidad.",
    intents: ["plan-cuentas"],
    modules: ["contabilidad"],
    level: "company",
    typicalRoles: ["OWNER / ADMIN", "Contabilidad"],
    permissionHint: "Company finance + módulo Contabilidad.",
    where: { menu: "Contabilidad → Plan de cuentas" },
    hrefs: [{ kind: "company", path: "/contabilidad/cuentas", label: "Plan de cuentas" }],
    steps: [
      "Contabilidad → Cuentas.",
      "Si está vacío: Aplicar plantilla AR.",
      "Revisá reglas de mapeo en Contabilidad → Reglas.",
    ],
    relatedSlugs: ["contabilizar-asientos", "puesta-en-marcha-contable"],
    keywords: ["plan de cuentas", "plantilla", "cuentas contables"],
    guideRef: "§15 · §0.1",
  },
  {
    slug: "contabilizar-asientos",
    title: "Contabilizar asientos (DRAFT ≠ POSTED)",
    summary: "Los asientos nacen en borrador solos; hay que Contabilizarlos para los libros.",
    intents: ["contabilizar", "revertir-asiento"],
    modules: ["contabilidad"],
    level: "company",
    typicalRoles: ["Contabilidad", "Finanzas", "ADMIN"],
    where: { menu: "Contabilidad → Asientos" },
    hrefs: [
      { kind: "company", path: "/contabilidad/asientos", label: "Asientos" },
      { kind: "company", path: "/contabilidad", label: "Hub contabilidad" },
    ],
    steps: [
      "Tras emitir factura / pagar / cobrar, revisá Borradores pendientes en el hub.",
      "Abrí el asiento → Contabilizar (POSTED). Nunca se auto-posta.",
      "Si el asiento tiene origen operativo: montos bloqueados; sí podés ajustar cuentas y textos.",
      "Corrección: Revertir un POSTED (crea asiento de reversa). Anular borrador: Anular borrador.",
      "Libro diario / sumas y saldos / ESP / resultados solo usan POSTED.",
    ],
    effects: [
      "Factura venta/proveedor, cobranza, pago, transferencia e ingreso solo-caja generan auto-DRAFT.",
      "Consumo de stock / recepción: aún sin auto-DRAFT.",
    ],
    pitfalls: [
      "Creer que «apareció el borrador» = ya está contabilizado.",
      "Si hay POSTED sin reverso, anular el documento origen se bloquea.",
    ],
    relatedSlugs: [
      "cerrar-el-mes",
      "aplicar-plantilla-plan-de-cuentas",
      "leer-reportes-contables",
    ],
    keywords: [
      "contabilizar",
      "asiento",
      "draft",
      "posted",
      "borrador",
      "revertir",
      "revertir asiento",
      "anular borrador",
    ],
    guideRef: "§15.2 · §16 · §17",
  },
  {
    slug: "leer-reportes-contables",
    title: "Leer reportes contables (diario, sumas, ESP, resultados)",
    summary: "Libros gerenciales internos: solo asientos POSTED. No sustituyen AFIP.",
    intents: ["reportes-contables"],
    modules: ["contabilidad"],
    level: "company",
    typicalRoles: ["Contabilidad", "Finanzas", "OWNER / ADMIN"],
    permissionHint: "Company finance + módulo Contabilidad.",
    where: { menu: "Contabilidad → Libro diario / Sumas y saldos / Situación / Resultados" },
    hrefs: [
      { kind: "company", path: "/contabilidad/libro-diario", label: "Libro diario" },
      { kind: "company", path: "/contabilidad/sumas-y-saldos", label: "Sumas y saldos" },
      { kind: "company", path: "/contabilidad/situacion-patrimonial", label: "Situación patrimonial" },
      { kind: "company", path: "/contabilidad/estado-resultados", label: "Estado de resultados" },
    ],
    steps: [
      "Contabilizá los borradores del período primero.",
      "Libro diario: asientos POSTED del período.",
      "Sumas y saldos: trial balance por período.",
      "Situación patrimonial: ESP al corte (asOfDate).",
      "Estado de resultados: EERR del período.",
      "Exportá CSV/PDF/XLSX desde cada reporte si hace falta.",
    ],
    pitfalls: ["Si los reportes están vacíos, probablemente faltan Contabilizar borradores."],
    relatedSlugs: ["contabilizar-asientos", "aplicar-plantilla-plan-de-cuentas", "cerrar-el-mes"],
    keywords: [
      "libro diario",
      "sumas y saldos",
      "trial balance",
      "situacion patrimonial",
      "esp",
      "estado de resultados",
      "eerr",
      "reportes contables",
    ],
    guideRef: "§15.1 · §15.2",
  },
  {
    slug: "cerrar-el-mes",
    title: "Cerrar el mes",
    summary: "Cierre de período GL: bloquea caja y asientos del mes. Distinto del cierre de GG.",
    intents: ["cerrar-mes"],
    modules: ["contabilidad"],
    level: "company",
    typicalRoles: ["OWNER", "ADMIN"],
    where: { menu: "Contabilidad → Cierres" },
    hrefs: [{ kind: "company", path: "/contabilidad/cierres", label: "Cierres" }],
    steps: [
      "Antes: cobros/pagos OK → borradores contabilizados → conciliaciones cerradas.",
      "Contabilidad → Cierres → Cerrar período.",
      "Para corregir: Reabrir con motivo auditado (OWNER/ADMIN).",
    ],
    figure: {
      src: "/help/mapa-cerrar-el-mes.png",
      alt: "Bloqer — Cerrar el mes",
      caption: "Operar → contabilizar → conciliar → cerrar. Reabrir exige motivo.",
    },
    pitfalls: [
      "No confundas cierre de período con cierre de GG (/finanzas/gastos-generales).",
      "No cierres el mes antes de conciliar y postear.",
    ],
    relatedSlugs: [
      "conciliar-el-banco",
      "contabilizar-asientos",
      "imputar-gastos-generales",
      "leer-reportes-contables",
    ],
    keywords: ["cierre", "cerrar mes", "periodo", "reabrir"],
    guideRef: "§15.3",
  },
  {
    slug: "inventario-corporativo-basico",
    title: "Inventario corporativo (productos y movimientos)",
    summary: "Productos, depósitos, movimientos append-only y transferencias entre depósitos.",
    intents: ["inventario"],
    modules: ["inventario"],
    level: "company",
    typicalRoles: ["Depósito", "Compras", "ADMIN"],
    permissionHint: "Permiso de Inventario + módulo habilitado.",
    where: { menu: "General → Inventario" },
    hrefs: [
      { kind: "company", path: "/inventario", label: "Inventario" },
      { kind: "company", path: "/inventario/productos", label: "Productos" },
      { kind: "company", path: "/inventario/depositos", label: "Depósitos" },
      { kind: "company", path: "/inventario/movimientos", label: "Movimientos" },
      { kind: "company", path: "/inventario/transferencias", label: "Transferencias" },
      { kind: "company", path: "/inventario/reportes", label: "Reportes" },
    ],
    steps: [
      "Inventario → Productos: alta de ítems.",
      "Depósitos: ubicaciones físicas.",
      "Movimientos: ledger append-only (el saldo se calcula sumando movimientos).",
      "Transferencias: entre depósitos.",
      "Reportes: Stock actual y Movimientos confirmados (exportar CSV/PDF).",
      "En obra, las recepciones de OC también ingresan stock.",
    ],
    pitfalls: [
      "No hay valuación FIFO/promedio configurable aún: el costo se toma de la compra.",
    ],
    relatedSlugs: ["recibir-una-oc", "registrar-consumo-materiales"],
    keywords: [
      "inventario",
      "stock",
      "productos",
      "depositos",
      "almacen",
      "kardex",
      "transferencias",
      "reportes inventario",
      "stock actual",
    ],
    guideRef: "§14",
  },
  {
    slug: "usar-notificaciones",
    title: "Usar notificaciones (campana)",
    summary: "Inbox personal desde la campana del encabezado. No hay ítem en el menú lateral.",
    intents: ["notificaciones"],
    modules: ["general"],
    level: "both",
    typicalRoles: ["Todos"],
    where: { menu: "Campana del encabezado → Ver todas" },
    hrefs: [{ kind: "company", path: "/notificaciones", label: "Inbox de notificaciones" }],
    steps: [
      "Abrí la campana (badge si hay no leídas).",
      "Ver todas → /notificaciones (filtros Todas / No leídas / Leídas / Archivadas).",
      "Compras: Nueva solicitud (a quien aprueba SC/OC), OC pendiente / aprobada / confirmada. Si podés recibir, el aviso de OC confirmada abre el formulario de recepción.",
      "Compras — vencimientos ([D-097]): OC con entrega prevista pasada llegan a quien recepciona; SC con fecha requerida pasada llegan a compras/aprobadores; OC recibida sin factura llega a Administración (EDIT|APPROVE AP). Todas llevan CC OWNER/ADMIN y se repiten a diario con dedup 7 días.",
      "Libro de obra: Parte pendiente / Parte devuelto / Parte aprobado también llegan por email.",
      "OWNER/ADMIN: Alertas operativas en /notificaciones/alertas (cron diario 12:00 UTC). Todas las alertas operativas (AR/AP vencidas, stock negativo, certificaciones sin factura, uploads pendientes, compras demoradas, D-097) generan campana + email; el email queda en /notificaciones/emails filtrando por OPERATIONAL_ALERT.",
      "En mobile: Más → Notificaciones. La cola de acciones (Pendientes) es otra cosa: no confundir con esta campana.",
    ],
    relatedSlugs: ["revisar-pendientes", "errores-operativos-frecuentes", "cargar-libro-de-obra", "asignar-equipo-de-obra", "recibir-una-oc"],
    keywords: [
      "notificaciones",
      "campana",
      "alertas",
      "inbox",
      "avisos",
      "parte pendiente",
      "email",
      "registrar recepcion",
      "oc confirmada",
      "listo para pagar",
      "entrega vencida",
      "fecha requerida vencida",
      "oc sin factura",
      "cron",
      "alertas operativas",
      "operational_alert",
    ],
    guideRef: "§1.4",
  },
  {
    slug: "revisar-pendientes",
    title: "Revisar pendientes",
    summary:
      "Portero personal: aprobaciones y follow-through de compras en etapas (cotizar → aprobación → confirmar → recibir → facturar). El globo muestra cuántas te quedan a vos.",
    intents: ["pendientes", "notificaciones"],
    modules: ["general", "compras", "libro-obra", "certificaciones"],
    level: "both",
    typicalRoles: ["OWNER / ADMIN", "PM", "Compras", "Depósito"],
    where: { menu: "General → Pendientes (empresa) o Resumen → Pendientes (obra)" },
    hrefs: [
      { kind: "company", path: "/pendientes", label: "Pendientes de la empresa" },
      { kind: "project", suffix: "/pendientes", label: "Pendientes de esta obra" },
    ],
    steps: [
      "En el menú lateral, General → Pendientes (/pendientes): todas las obras. El globo rojo es tu recuento (en desktop también en la sección General si está plegada).",
      "En mobile, el ítem Pendientes de la barra inferior muestra el mismo globo (9+ si hay más de nueve).",
      "Dentro de un proyecto, Resumen → Pendientes lista solo esa obra; el globo de ese ítem es el recuento de esa obra.",
      "Filtro Compras: etapas Cotizar → **Aprobación** → Confirmar → Recibir → Facturar. CTAs: Cotizar / Elegir cotización; **Aprobar** o **Aprobar y comprometer** (si política [D-107]); Confirmar al proveedor (reserva $); Recibir (abre el formulario); **Registrar factura** o **Completar factura** (abre la OC / borrador).",
      "OC recibida sin factura aparece en Pendientes apenas hay recepción confirmada (EDIT AP). Si ya hay borrador ([D-108]), el CTA es Completar factura. La alerta/campana diaria puede esperar unos días (SLA configurable).",
      "Ítems vencidos ([D-097]) traen un badge rojo Vencida N d: OC con entrega prevista pasada, SC con fecha requerida pasada.",
      "También partes de libro de obra y certificaciones que vos podés aprobar.",
      "El número no es el mismo para todos: solo cuenta lo que tu rol puede cerrar (p. ej. un PM no ve OC por aprobar; Depósito ve recepciones; un VIEWER ve 0).",
      "No es el historial de la campana: eso sigue en Notificaciones. CxP «Listo para pagar» también va por la campana, no por este globo.",
    ],
    effects: [
      "El globo se actualiza al cargar la app y cada 30 s mientras la pestaña está visible.",
    ],
    pitfalls: [
      "El Equipo de obra (roster) no filtra esta bandeja: define avisos de partes, no quién ve Pendientes.",
      "Si no tenés permiso para ninguna de esas fuentes, el globo no aparece.",
      "Un PM puede ver SC en Pendientes aunque la campana de «Nueva solicitud» vaya a quien aprueba compras.",
      "Aprobar ≠ Comprometer: Confirmar al proveedor (o Aprobar y comprometer / Autorizar y comprometer con políticas) es lo que reserva $.",
    ],
    relatedSlugs: [
      "usar-notificaciones",
      "asignar-equipo-de-obra",
      "cargar-libro-de-obra",
      "solicitud-de-compra",
      "orden-de-compra-y-afectar-edt",
      "recibir-una-oc",
      "factura-desde-oc",
      "circuito-comprar-material-hasta-pagarlo",
    ],
    keywords: [
      "pendientes",
      "bandeja de pendientes",
      "portero",
      "globo",
      "numero de pendientes",
      "inbox de acciones",
      "por revisar",
      "cotizar",
      "aprobar",
      "confirmar",
      "confirmar al proveedor",
      "recepcion",
      "deposito",
      "sc por cotizar",
      "oc por confirmar",
      "oc por recibir",
      "oc sin factura",
      "recibida sin factura",
      "vencida",
      "vencimiento",
      "registrar factura",
    ],
    guideRef: "§1.2",
  },
  {
    slug: "configurar-empresa-logo-zona",
    title: "Configurar logo, zona horaria y moneda",
    summary: "Datos de visualización de la empresa en Configuración → General.",
    intents: ["configurar-empresa"],
    modules: ["configuracion"],
    level: "company",
    typicalRoles: ["OWNER", "ADMIN"],
    permissionHint: "OWNER/ADMIN editan preferencias de visualización.",
    where: { menu: "Configuración → General" },
    hrefs: [{ kind: "company", path: "/configuracion", label: "Configuración" }],
    steps: [
      "Configuración → General.",
      "Nombre a mostrar, moneda base y zona horaria (desplegable con GMT).",
      "Logo opcional (PNG/JPEG/WebP horizontal): reemplaza Bloqer en el menú y aparece en PDF.",
      "La zona se usa en Registro de actividad y reportes programados.",
    ],
    relatedSlugs: ["invitar-un-usuario", "que-ve-cada-rol"],
    keywords: ["logo", "zona horaria", "moneda", "configuracion", "marca"],
    guideRef: "§1.3",
  },
  {
    slug: "imputar-gastos-generales",
    title: "Imputar gastos generales",
    summary: "Overhead corporativo que afecta rentabilidad neta (independiente del cierre GL).",
    intents: ["gastos-generales"],
    modules: ["finanzas"],
    level: "company",
    typicalRoles: ["Finanzas", "OWNER / ADMIN"],
    where: { menu: "Finanzas → Imputación GG" },
    hrefs: [{ kind: "company", path: "/finanzas/gastos-generales", label: "Imputación GG" }],
    steps: [
      "Finanzas → Imputación GG.",
      "Imputá / cerrá según el flujo de la pantalla.",
      "No es el cierre de período contable.",
    ],
    relatedSlugs: ["cerrar-el-mes", "gasto-corporativo", "ver-rentabilidad-de-obra"],
    keywords: ["gastos generales", "gg", "overhead", "imputacion"],
    guideRef: "§14 · §16",
  },
  {
    slug: "errores-operativos-frecuentes",
    title: "Errores operativos frecuentes",
    summary: "Atajos incorrectos que más confunden: roles, Solo caja, OC vs subcontrato, doble conteo.",
    intents: ["errores-frecuentes"],
    modules: ["general", "directorio", "compras", "finanzas"],
    level: "both",
    typicalRoles: ["Todos"],
    where: { menu: "Ayuda → esta ficha" },
    hrefs: [{ kind: "company", path: "/ayuda", label: "Buscar en Ayuda" }],
    steps: [
      "Empleado ≠ Proveedor solo para pagarle → ver «Pagar un sueldo».",
      "Reintegro ≠ Solo caja (ingreso) → ver «Reintegrar un gasto».",
      "Subcontrato ≠ OC → ver «Certificar y pagar un subcontrato».",
      "OC confirmada = Comprometido; factura = Devengado; no sumes ambos.",
      "Borrador contable ≠ contabilizado.",
    ],
    relatedSlugs: [
      "proveedor-empleado-o-subcontratista",
      "pagar-un-sueldo",
      "reintegrar-gasto-a-empleado",
      "certificar-y-pagar-subcontrato",
      "leer-edt-y-costos",
      "afectaciones-comprometido-devengado-pagado",
      "contabilizar-asientos",
      "limitaciones-actuales-de-bloqer",
      "checklist-habitos-por-rol",
    ],
    keywords: ["error", "errores", "equivocado", "como no", "faq"],
    guideRef: "§17",
  },
];
