import type { HelpArticle } from "../types";

export const DIRECTORY_ARTICLES: HelpArticle[] = [
  {
    slug: "cargar-un-proveedor",
    title: "Cargar un proveedor",
    summary:
      "Alta en el Directorio con rol Proveedor para usarlo en órdenes de compra y facturas de compra.",
    intents: ["cargar-proveedor", "cargar-contacto"],
    modules: ["directorio"],
    level: "company",
    typicalRoles: ["Administración", "Compras", "OWNER / ADMIN"],
    permissionHint: "Necesitás permiso para ver/editar Directorio.",
    where: { menu: "General → Directorio → + Nuevo contacto" },
    hrefs: [
      { kind: "company", path: "/directorio/nuevo?role=SUPPLIER", label: "Nuevo contacto (Proveedor)" },
      { kind: "company", path: "/directorio", label: "Ir al Directorio" },
    ],
    steps: [
      "Abrí Directorio.",
      "Pulsá + Nuevo contacto (o usá /directorio/nuevo?role=SUPPLIER).",
      "Completá nombre / razón social y datos fiscales si aplica.",
      "Marcá el rol Proveedor (podés sumar otros roles al mismo contacto).",
      "Guardá. El contacto queda activo y disponible en OC y en «A quién se le paga».",
    ],
    effects: [
      "Aparece en selectores de proveedor de OC y cotizaciones: se busca por razón social o nombre fantasía.",
      "Puede ser payee de facturas de proveedor / gastos.",
    ],
    pitfalls: [
      "No crees un contacto nuevo solo por rol: un mismo CUIT puede ser Proveedor + Subcontratista.",
      "Si es personal interno que solo cobra sueldo/reintegro, usá Empleado (no Proveedor).",
      "Si lo cargaste como Cliente, no aparece en «A quién se le paga»: asignale rol Proveedor en la ficha.",
    ],
    relatedSlugs: [
      "proveedor-empleado-o-subcontratista",
      "un-contacto-varios-roles",
      "cargar-un-empleado",
      "reporte-proveedores-de-obra",
    ],
    keywords: [
      "proveedor",
      "cargar proveedor",
      "alta proveedor",
      "dar de alta un proveedor",
      "como cargo un proveedor",
      "directorio",
      "supplier",
      "ferretero",
      "no aparece en facturas",
      "no aparece proveedor",
    ],
    guideRef: "§3",
  },
  {
    slug: "cargar-un-cliente",
    title: "Cargar un cliente",
    summary: "Sin un contacto Cliente activo no podés crear una obra.",
    intents: ["cargar-cliente", "cargar-contacto"],
    modules: ["directorio", "proyectos"],
    level: "company",
    typicalRoles: ["Administración", "OWNER / ADMIN", "Comercial"],
    permissionHint: "Necesitás permiso de Directorio.",
    where: { menu: "General → Directorio → + Nuevo contacto" },
    hrefs: [
      { kind: "company", path: "/directorio/nuevo?role=CLIENT", label: "Nuevo contacto (Cliente)" },
    ],
    steps: [
      "Abrí Directorio → + Nuevo contacto (o ?role=CLIENT).",
      "Marcá el rol Cliente.",
      "Guardá el contacto activo.",
      "Al crear el proyecto (o una factura de venta), buscalo por razón social o nombre fantasía.",
    ],
    effects: ["Habilita el alta de proyecto y las cobranzas / CxC de obra."],
    pitfalls: ["No dupliques el mandante: un contacto, rol Cliente."],
    relatedSlugs: ["crear-y-activar-una-obra", "un-contacto-varios-roles"],
    keywords: ["cliente", "cargar cliente", "mandante", "comitente", "directorio", "razón social", "nombre fantasía"],
    guideRef: "§3",
  },
  {
    slug: "cargar-un-empleado",
    title: "Cargar un empleado",
    summary:
      "Personal interno para sueldos como costo y reintegros. No hace falta marcarlo como Proveedor.",
    intents: ["cargar-empleado", "cargar-contacto", "pagar-sueldo"],
    modules: ["directorio", "finanzas"],
    level: "company",
    typicalRoles: ["Administración", "OWNER / ADMIN"],
    permissionHint: "Necesitás permiso de Directorio.",
    where: { menu: "General → Directorio → + Nuevo contacto" },
    hrefs: [
      { kind: "company", path: "/directorio/nuevo?role=EMPLOYEE", label: "Nuevo contacto (Empleado)" },
    ],
    steps: [
      "Abrí Directorio → + Nuevo contacto (?role=EMPLOYEE).",
      "Marcá el rol Empleado y dejalo activo.",
      "Para pagarle: Finanzas → Transacciones → Gasto / factura → «A quién se le paga» = el empleado.",
    ],
    effects: ["Aparece en el picker de gasto como «Razón social · Empleado» (fantasía al lado si es distinta)."],
    pitfalls: [
      "No lo marques Proveedor solo para pagarle (ensucia el listado de OC).",
      "Monotributista que te factura → rol Proveedor (y Empleado si también es de la casa).",
    ],
    relatedSlugs: ["pagar-un-sueldo", "reintegrar-gasto-a-empleado", "proveedor-empleado-o-subcontratista"],
    keywords: ["empleado", "cargar empleado", "personal", "directorio"],
    guideRef: "§3",
  },
  {
    slug: "cargar-un-subcontratista",
    title: "Cargar un subcontratista",
    summary: "Contacto con rol Subcontratista para paquetes de ejecución (no es una OC).",
    intents: ["cargar-subcontratista", "cargar-contacto", "subcontrato"],
    modules: ["directorio", "subcontratos"],
    level: "company",
    typicalRoles: ["Administración", "PM", "Compras"],
    permissionHint: "Necesitás permiso de Directorio.",
    where: { menu: "General → Directorio → + Nuevo contacto" },
    hrefs: [
      {
        kind: "company",
        path: "/directorio/nuevo?role=SUBCONTRACTOR",
        label: "Nuevo contacto (Subcontratista)",
      },
    ],
    steps: [
      "Abrí Directorio → + Nuevo contacto (?role=SUBCONTRACTOR).",
      "Marcá Subcontratista (podés sumar Proveedor si también vende materiales).",
      "En la obra: Finanzas del proyecto → Subcontratos → Nuevo subcontrato.",
    ],
    effects: ["Queda disponible al crear un Subcontrato (buscá por razón social o nombre fantasía)."],
    pitfalls: ["No pagues un paquete de obra con OC ni con gasto genérico: usá el flujo de subcontrato."],
    relatedSlugs: ["crear-un-subcontrato", "certificar-y-pagar-subcontrato", "proveedor-empleado-o-subcontratista"],
    keywords: ["subcontratista", "cargar subcontratista", "albañil", "electricista"],
    guideRef: "§3",
  },
  {
    slug: "un-contacto-varios-roles",
    title: "Un contacto, varios roles",
    summary: "No des de alta la misma persona dos veces. Un contacto puede ser Cliente, Proveedor, Empleado, etc.",
    intents: ["roles-contacto", "cargar-contacto"],
    modules: ["directorio"],
    level: "company",
    typicalRoles: ["Administración"],
    where: { menu: "General → Directorio → editar contacto" },
    hrefs: [{ kind: "company", path: "/directorio", label: "Ir al Directorio" }],
    steps: [
      "Buscá el contacto existente.",
      "Editá y marcá todos los roles que correspondan.",
      "Guardá. Los selectores filtran por rol según la pantalla y se buscan por razón social o nombre fantasía (no por CUIT).",
    ],
    pitfalls: ["Duplicar contactos parte los datos y complica pagos/OC."],
    relatedSlugs: ["proveedor-empleado-o-subcontratista", "cargar-un-proveedor"],
    keywords: ["roles", "varios roles", "duplicar contacto", "mismo cuit"],
    guideRef: "§3",
  },
  {
    slug: "proveedor-empleado-o-subcontratista",
    title: "¿Proveedor, empleado o subcontratista?",
    summary: "Elegí el rol según cómo operás con esa persona en Bloqer (D-089).",
    intents: ["roles-contacto", "cargar-proveedor", "cargar-empleado", "cargar-subcontratista"],
    modules: ["directorio", "finanzas", "compras"],
    level: "both",
    typicalRoles: ["Administración", "Compras", "Finanzas"],
    where: { menu: "General → Directorio" },
    hrefs: [{ kind: "company", path: "/directorio", label: "Ir al Directorio" }],
    steps: [
      "Proveedor: quien nos factura o vende (incluye monotributista) → OC y/o factura de proveedor.",
      "Empleado: personal interno → gasto sin OC (sueldo como costo o reintegro).",
      "Subcontratista: paquete de ejecución → Subcontrato → certificar → factura → CxP.",
      "Quien vende materiales y ejecuta un paquete → Proveedor + Subcontratista.",
    ],
    pitfalls: [
      "Marcar al empleado como Proveedor solo para pagarle ensucia el listado de OC.",
      "Pagar un subcontrato con OC o gasto genérico es el camino incorrecto.",
    ],
    relatedSlugs: [
      "cargar-un-proveedor",
      "cargar-un-empleado",
      "cargar-un-subcontratista",
      "pagar-un-sueldo",
      "circuito-comprar-material-hasta-pagarlo",
    ],
    keywords: [
      "monotributista",
      "diferencia proveedor empleado",
      "que rol",
      "quien es proveedor",
    ],
    guideRef: "§3 · §9 · D-089",
  },
];
