import type { HelpArticle } from "../types";

export const SUBCONTRACT_AR_ARTICLES: HelpArticle[] = [
  {
    slug: "crear-un-subcontrato",
    title: "Crear un subcontrato",
    summary: "Paquete de ejecución con subcontratista del Directorio. No es una OC.",
    intents: ["subcontrato"],
    modules: ["subcontratos"],
    level: "project",
    typicalRoles: ["PM", "Compras", "Administración"],
    where: { menu: "Compras → Subcontratos" },
    hrefs: [{ kind: "project", suffix: "/subcontratos", label: "Subcontratos" }],
    steps: [
      "Prerrequisito: contacto con rol Subcontratista.",
      "Compras → Subcontratos → Nuevo (buscá al subcontratista por razón social o nombre fantasía).",
      "Alcance e imputación a partidas (categoría SUB en APU cuando corresponda).",
    ],
    relatedSlugs: ["cargar-un-subcontratista", "certificar-y-pagar-subcontrato"],
    keywords: ["subcontrato", "crear subcontrato", "paquete", "compromisos"],
    guideRef: "§10",
  },
  {
    slug: "certificar-y-pagar-subcontrato",
    title: "Certificar y pagar un subcontrato",
    summary: "El caminito: certificar → ¿aprueba? → factura → ¿emitís? → CxP → ¿fondos? → pagar.",
    intents: ["certificar-subcontrato", "pagar-cxp"],
    modules: ["subcontratos", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas"],
    where: { menu: "Compras → Subcontratos" },
    hrefs: [
      { kind: "project", suffix: "/subcontratos", label: "Subcontratos" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
    ],
    stepsTitle: "Caminito",
    steps: [
      "¿Hay subcontratista en Directorio? Si no → cargalo con ese rol. Si sí → Nuevo subcontrato (alcance + partidas SUB).",
      "Certificación del período → Emitir. ¿Aprueba? Si no → Rechazada, no hay CxP.",
      "Si aprueba → factura AP en borrador (payee = subcontratista). ¿Emitís? Si no → no hay CxP ni se paga.",
      "Emitir = Devengado + CxP. ¿Hay fondos y mes abierto? Si sí → Pagado. Si no → Bloqer bloquea.",
    ],
    pitfalls: ["No pagues el subcontrato creando una OC ni eligiendo al subcontratista en el gasto genérico."],
    figure: {
      src: "/help/mapa-flujo-subcontrato-si-no.png",
      alt: "Bloqer — Subcontrato: si esto, entonces aquello",
      caption: "No es una OC. La lámina con roles está en Ayuda → Mapas.",
    },
    relatedSlugs: ["crear-un-subcontrato", "pagar-una-cuenta-por-pagar"],
    keywords: ["certificar subcontrato", "pagar subcontrato", "certificacion sub"],
    guideRef: "§10",
  },
  {
    slug: "emitir-y-aprobar-certificacion",
    title: "Emitir y aprobar certificación al cliente",
    summary: "Avance certificado sobre presupuesto APPROVED/CLOSED.",
    intents: ["certificacion-cliente"],
    modules: ["certificaciones"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Operación → Certificaciones" },
    hrefs: [{ kind: "project", suffix: "/certificaciones", label: "Certificaciones" }],
    steps: [
      "Prerrequisito: presupuesto APPROVED o CLOSED.",
      "Nueva certificación con período.",
      "Cargá Δ% físico y/o $ económico por partida.",
      "Emitir (ISSUED, inmutable) → Aprobar (APPROVED) o rechazar según el mandante.",
    ],
    relatedSlugs: ["facturar-una-certificacion", "aprobar-el-presupuesto"],
    keywords: ["certificacion", "certificar", "avance cliente", "certificado de avance", "certificado"],
    guideRef: "§11",
  },
  {
    slug: "facturar-una-certificacion",
    title: "Facturar una certificación",
    summary: "El caminito: aprobar no cobra. Emitir factura → CxC → cobrar (caja recién al confirmar).",
    intents: ["facturar-certificacion"],
    modules: ["certificaciones", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas", "Administración"],
    where: { menu: "Operación → Certificaciones / Facturas emitidas" },
    hrefs: [
      { kind: "project", suffix: "/certificaciones", label: "Certificaciones" },
      { kind: "project", suffix: "/facturas", label: "Facturas emitidas" },
    ],
    stepsTitle: "Caminito",
    steps: [
      "¿Presupuesto APPROVED o CLOSED? Si no → no se certifica con normalidad.",
      "Nueva certificación → cargar avance. ¿Supera 100%? Pública → Bloqer bloquea. Privada → sigue con nota obligatoria.",
      "Emitir (inmutable). ¿El mandante aprueba? Si no → Rechazada, no se factura. Si sí → APPROVED (todavía no hay CxC).",
      "CTA Emitir factura → CxC. Cobrar desde Cuentas por cobrar. Solo la cobranza confirmada mueve caja. No hay Cobrar ahora en el alta de factura de obra.",
    ],
    figure: {
      src: "/help/mapa-flujo-certificar-cobrar-si-no.png",
      alt: "Bloqer — Certificar y cobrar: si esto, entonces aquello",
      caption: "Aprobar no cobra. La lámina con roles está en Ayuda → Mapas.",
    },
    relatedSlugs: ["cobrar-una-cxc-de-obra", "emitir-y-aprobar-certificacion"],
    keywords: ["facturar certificacion", "factura venta", "emitir factura"],
    guideRef: "§11.3 · §12.1",
  },
  {
    slug: "cobrar-una-cxc-de-obra",
    title: "Cobrar una CxC de obra",
    summary: "Cobranza confirmada acredita tesorería (INFLOW).",
    intents: ["cobrar"],
    modules: ["finanzas", "tesoreria"],
    level: "project",
    typicalRoles: ["Finanzas", "Administración", "Tesorería"],
    where: { menu: "Finanzas del proyecto → Cuentas por cobrar → Cobrar" },
    hrefs: [{ kind: "project", suffix: "/cuentas-por-cobrar", label: "Cuentas por cobrar" }],
    steps: [
      "CxC del proyecto → detalle → Cobrar.",
      "Cuenta, fecha, monto (2 decimales; usá el saldo que muestra el sistema), método y referencia.",
      "Confirmá. Solo la cobranza confirmada mueve caja.",
    ],
    relatedSlugs: ["facturar-una-certificacion", "ingreso-corporativo-con-factura"],
    keywords: [
      "cobrar",
      "cobranza",
      "cxc",
      "cuenta por cobrar",
      "cobrar factura",
      "cuenta corriente",
    ],
    guideRef: "§12.1",
  },
  {
    slug: "anticipo-o-venta-rapida",
    title: "Anticipo / venta rápida de obra",
    summary: "Factura + CxC (+ cobro opcional) en un paso desde la obra.",
    intents: ["anticipo", "cobrar"],
    modules: ["finanzas", "certificaciones"],
    level: "project",
    typicalRoles: ["Finanzas", "Administración", "PM"],
    where: { menu: "Finanzas del proyecto → Facturas emitidas → Anticipo" },
    hrefs: [{ kind: "project", suffix: "/facturas/anticipo/nueva", label: "Nuevo anticipo" }],
    steps: [
      "Entrá a la obra → Facturas emitidas.",
      "Alta de anticipo / venta rápida (`/facturas/anticipo/nueva`).",
      "Completá cliente (buscá por razón social o nombre fantasía) y líneas; cobro opcional si tenés permiso de tesorería.",
      "Para facturar una certificación aprobada usá el CTA Emitir factura (otro flujo).",
    ],
    relatedSlugs: ["facturar-una-certificacion", "cobrar-una-cxc-de-obra"],
    keywords: ["anticipo", "venta rapida", "adelanto", "factura anticipo"],
    guideRef: "§12.1",
  },
  {
    slug: "ingreso-corporativo-con-factura",
    title: "Ingreso corporativo con factura",
    summary: "Ventas sin obra (capacitaciones, materiales de estructura) con CxC.",
    intents: ["ingreso-corporativo"],
    modules: ["finanzas"],
    level: "company",
    typicalRoles: ["Finanzas", "Administración"],
    permissionHint: "Rol de company finance.",
    where: { menu: "Finanzas → Transacciones → Ingreso / cobro" },
    hrefs: [{ kind: "company", path: "/finanzas/transacciones", label: "Transacciones" }],
    steps: [
      "Finanzas → Transacciones → Registrar → tab Ingreso / cobro.",
      "Modo Factura / cuenta por cobrar: cliente, líneas (precio, Desc. % opcional, IVA), vencimiento. El chip Clase muestra Ingreso corporativo.",
      "Opcional: Cobrar ahora (ingreso a caja) si tenés permiso de tesorería.",
    ],
    relatedSlugs: ["ingreso-solo-caja", "cobrar-una-cxc-de-obra", "descuento-porcentual-en-lineas", "clase-de-documento-financiero"],
    keywords: ["ingreso corporativo", "factura sin obra", "ar income", "clase"],
    guideRef: "§12.0 · §12.1",
  },
  {
    slug: "ingreso-solo-caja",
    title: "Ingreso solo caja (sin CxC)",
    summary: "Aportes, préstamos recibidos, devoluciones a la empresa. No es un reintegro a empleado. Clase: Ingreso solo caja.",
    intents: ["ingreso-solo-caja"],
    modules: ["finanzas", "tesoreria"],
    level: "company",
    typicalRoles: ["Finanzas", "Tesorería"],
    where: { menu: "Finanzas → Transacciones → Ingreso / cobro → Solo caja" },
    hrefs: [{ kind: "company", path: "/finanzas/transacciones", label: "Transacciones" }],
    steps: [
      "Transacciones → Ingreso / cobro → modo Solo caja (TREASURY_INFLOW). Clase: Ingreso solo caja (badge verde).",
      "Cuenta, monto y fecha.",
      "En el listado, clic en la descripción para leer el texto completo (este tipo no tiene documento origen que abrir).",
    ],
    pitfalls: [
      "Reintegrar a un empleado es un EGRESO (Gasto / factura), no un ingreso Solo caja.",
      "Transacciones lista movimientos de caja, no facturas impagas.",
    ],
    relatedSlugs: ["reintegrar-gasto-a-empleado", "ingreso-corporativo-con-factura", "clase-de-documento-financiero"],
    keywords: ["solo caja", "aporte", "prestamo", "treasury inflow", "clase"],
    guideRef: "§12.0 · §12.1 · §17",
  },
];

export const AP_ARTICLES: HelpArticle[] = [
  {
    slug: "pagar-un-sueldo",
    title: "Pagar un sueldo (registro de costo)",
    summary:
      "El caminito: empleado en Directorio → gasto → pagar ahora o dejar CxP. No es nómina.",
    intents: ["pagar-sueldo"],
    modules: ["finanzas", "directorio"],
    level: "company",
    typicalRoles: ["Administración", "Finanzas"],
    permissionHint: "Company finance + Directorio para el empleado.",
    where: { menu: "Finanzas → Transacciones → Gasto / factura" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "company", path: "/directorio/nuevo?role=EMPLOYEE", label: "Alta de empleado" },
    ],
    stepsTitle: "Caminito",
    steps: [
      "¿El contacto es Empleado activo en Directorio? Si no → no aparece para pagarle: cargalo con ese rol, no como Proveedor.",
      "Finanzas → Transacciones → Gasto / factura → A quién se le paga = el empleado → líneas del mes.",
      "¿Pagar ahora? Si sí y hay fondos → Pagado (factura + CxP saldada + egreso). Si no hay fondos → Bloqer bloquea.",
      "Si no pagás ahora → Emitir → CxP abierta → pagar después desde Cuentas por pagar.",
    ],
    effects: ["Mapeado al empleado. Si pagás: CxP saldada + egreso. Si no: CxP abierta."],
    figure: {
      src: "/help/mapa-flujo-sueldo-si-no.png",
      alt: "Bloqer — Pagar un sueldo: si esto, entonces aquello",
      caption: "No es nómina ni Solo caja. La lámina de pago corporativo está en Ayuda → Mapas.",
    },
    pitfalls: [
      "No marques al empleado como Proveedor solo para pagarle.",
      "No uses Solo caja (ingreso) para «pagar» un sueldo.",
      "Si el mes está cerrado, no se emite ni se paga.",
    ],
    relatedSlugs: [
      "cargar-un-empleado",
      "reintegrar-gasto-a-empleado",
      "proveedor-empleado-o-subcontratista",
    ],
    keywords: [
      "sueldo",
      "sueldos",
      "pagar sueldo",
      "nomina",
      "haberes",
      "salario",
      "empleado",
      "liquidacion",
      "liquidacion de sueldos",
    ],
    guideRef: "§12.2.1",
  },
  {
    slug: "reintegrar-gasto-a-empleado",
    title: "Reintegrar un gasto a un empleado",
    summary: "El empleado adelantó plata; la empresa se la devuelve (egreso, no Solo caja).",
    intents: ["reintegro"],
    modules: ["finanzas", "directorio"],
    level: "both",
    typicalRoles: ["Administración", "Finanzas", "PM"],
    where: { menu: "Transacciones / Facturas proveedor (obra)" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones (empresa)" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor (obra)" },
    ],
    steps: [
      "Empleado en Directorio con rol Empleado.",
      "Empresa: Transacciones → Gasto / factura → payee = empleado → Pagar ahora.",
      "Obra: Facturas proveedor del proyecto, sin OC, líneas con partida EDT, payee = empleado.",
    ],
    pitfalls: [
      "No uses Solo caja (ingreso) para reintegrar.",
      "Si el «empleado» es monotributista y te pasa factura C: cargalo como Proveedor.",
    ],
    relatedSlugs: ["pagar-un-sueldo", "gasto-de-obra-sin-oc", "ingreso-solo-caja"],
    keywords: ["reintegro", "reembolsar", "adelanto", "combustible", "ferreteria"],
    guideRef: "§12.2.2",
  },
  {
    slug: "gasto-de-obra-sin-oc",
    title: "Gasto de obra sin OC (costo directo)",
    summary:
      "Factura de proveedor de proyecto en modo Costo directo: partida EDT y tipo de costo; no baja el comprometido de una OC. Clase: Costo directo de obra.",
    intents: ["gasto-obra"],
    modules: ["finanzas", "compras"],
    level: "project",
    typicalRoles: ["PM", "Administración", "Finanzas"],
    where: { menu: "Finanzas del proyecto → Facturas proveedor → Nueva" },
    hrefs: [{ kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" }],
    stepsTitle: "Caminito",
    steps: [
      "¿Es material con OC o un paquete de ejecución? Si sí → usá el caminito de compras o el de subcontrato. Este camino es gasto directo.",
      "Facturas proveedor → Nueva → modo Costo directo. ¿Cada línea tiene partida hoja EDT? Si no → no se guarda.",
      "Payee: Proveedor o Empleado. Tipo de costo en cada línea. No baja el comprometido de una OC.",
      "Crear → Emitir = Devengado + CxP. ¿Pagar ahora? Si sí, hace falta fondos y mes abierto; si no, Bloqer bloquea. Si no pagás ahora, queda CxP.",
    ],
    figure: {
      src: "/help/mapa-flujo-costo-obra-si-no.png",
      alt: "Bloqer — Costo de obra: si esto, entonces aquello",
      caption: "Costo directo ≠ compra comprometida. Reintegro de obra = este mismo camino, payee Empleado.",
    },
    pitfalls: [
      "Costo directo no reduce el comprometido de una OC. Si compraste contra OC, usá Contra orden de compra.",
      "No uses Solo caja para reintegrar al capataz.",
    ],
    relatedSlugs: [
      "reintegrar-gasto-a-empleado",
      "circuito-comprar-material-hasta-pagarlo",
      "descuento-porcentual-en-lineas",
      "clase-de-documento-financiero",
    ],
    keywords: [
      "gasto obra",
      "sin oc",
      "costo directo",
      "factura chica",
      "partida edt",
      "boleta",
      "factura proveedor",
      "clase",
    ],
    guideRef: "§12.0 · §12.2",
  },
  {
    slug: "gasto-corporativo",
    title: "Gasto corporativo / factura de estructura",
    summary: "El caminito: si es de una obra, no es este camino. Sin EDT. Clase: Gasto general.",
    intents: ["gasto-corporativo"],
    modules: ["finanzas"],
    level: "company",
    typicalRoles: ["Administración", "Finanzas"],
    where: { menu: "Finanzas → Facturas y gastos / Transacciones" },
    hrefs: [
      { kind: "company", path: "/finanzas/facturas-proveedor", label: "Facturas y gastos" },
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
    ],
    stepsTitle: "Caminito",
    steps: [
      "¿El gasto tiene partida EDT de una obra? Si sí → usá Facturas proveedor del proyecto (costo de obra), no este camino.",
      "Facturas y gastos o Transacciones → Gasto / factura, sin proyecto. Clase: Gasto general.",
      "¿El payee es Proveedor o Empleado activo? Si no → no sale en el listado: asigná el rol. Cliente y Subcontratista no sirven acá.",
      "Crear / Emitir = Devengado + CxP. ¿Pagar ahora? Si sí y hay fondos → Pagado. Si no hay fondos → Bloqer bloquea. Si no pagás ahora → CxP.",
    ],
    figure: {
      src: "/help/mapa-flujo-gasto-empresa-si-no.png",
      alt: "Bloqer — Costo de empresa: si esto, entonces aquello",
      caption: "Sin obra y sin EDT. Imputar GG a obras es otro menú, no este alta.",
    },
    pitfalls: [
      "Si el contacto está en Directorio y no aparece, no tiene rol Proveedor o Empleado activo: asignalo en su ficha.",
    ],
    relatedSlugs: [
      "pagar-un-sueldo",
      "pagar-una-cuenta-por-pagar",
      "descuento-porcentual-en-lineas",
      "clase-de-documento-financiero",
    ],
    keywords: [
      "gasto corporativo",
      "estructura",
      "alquiler",
      "factura gasto",
      "gasto general",
      "no aparece proveedor",
      "no aparece en facturas",
      "clase",
    ],
    guideRef: "§12.0 · §12.2 · §14",
  },
  {
    slug: "clase-de-documento-financiero",
    title: "Clase de documento financiero",
    summary:
      "Qué significa el badge Clase en facturas, CxC/CxP y movimientos: se deriva sola; no se elige a mano.",
    intents: ["clase-documento"],
    modules: ["finanzas"],
    level: "both",
    typicalRoles: ["Finanzas", "Administración", "PM"],
    where: { menu: "Listados de facturas, CxC/CxP, Transacciones / Tesorería" },
    hrefs: [
      { kind: "company", path: "/finanzas/facturas-proveedor", label: "Facturas y gastos" },
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor (obra)" },
    ],
    steps: [
      "En listados y detalle vas a ver un badge Clase (venta de obra, compra comprometida, costo directo, gasto general, etc.). En caja, Pago es rojo e Ingreso / Cobranza verdes.",
      "En el alta, el chip «Se registrará como…» anticipa esa etiqueta según obra / OC / certificación / solo caja.",
      "En obra, al cargar factura de proveedor elegí Contra OC o Costo directo: eso define Compra comprometida vs Costo directo.",
      "Podés filtrar por Clase en los listados (?class=). En Transacciones (y en el extracto de cuenta) no hace falta filtrar por Origen: es el mismo eje técnico.",
    ],
    effects: [
      "No hay columna nueva en la base: la clase se calcula de projectId, OC, certificación, sourceType, etc.",
    ],
    pitfalls: [
      "No confundas Clase con la letra A/B/C/E del comprobante.",
      "«Tipo de documento» (NC/ND) todavía no existe: cuando exista será otro chip.",
      "Transacciones no lista facturas impagas: esas clases están en Facturas / CxC / CxP.",
    ],
    relatedSlugs: [
      "gasto-de-obra-sin-oc",
      "gasto-corporativo",
      "ingreso-corporativo-con-factura",
      "ingreso-solo-caja",
      "circuito-comprar-material-hasta-pagarlo",
    ],
    keywords: [
      "clase",
      "tipo de documento",
      "gasto",
      "compra",
      "venta",
      "generales",
      "costo directo",
      "comprometida",
      "overhead",
    ],
    guideRef: "§12.0",
  },
  {
    slug: "emitir-y-pagar-ahora",
    title: "Emitir y pagar ahora",
    summary: "Factura emitida + CxP + pago + egreso en un paso (requiere permiso de tesorería).",
    intents: ["emitir-y-pagar"],
    modules: ["finanzas", "tesoreria"],
    level: "both",
    typicalRoles: ["Finanzas", "Tesorería", "Administración"],
    where: { menu: "Factura proveedor / Transacciones" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor (obra)" },
    ],
    steps: [
      "Al crear/emitir, activá Emitir y pagar ahora (egreso de caja) / Pagar ahora.",
      "Elegí cuenta y fecha.",
      "Si no hay fondos suficientes, el sistema bloquea.",
    ],
    effects: ["Devengado + pagado + OUTFLOW; asientos DRAFT de factura y pago."],
    relatedSlugs: ["pagar-una-cuenta-por-pagar", "por-que-un-pago-se-bloquea"],
    keywords: ["emitir y pagar", "pagar ahora", "pago inmediato"],
    guideRef: "§12.2",
  },
  {
    slug: "pagar-una-cuenta-por-pagar",
    title: "Pagar una cuenta por pagar",
    summary: "Cadena Factura → Payable → Payment → OUTFLOW. Usá el saldo a 2 decimales.",
    intents: ["pagar-cxp"],
    modules: ["finanzas", "tesoreria"],
    level: "both",
    typicalRoles: ["Finanzas", "Tesorería", "Administración"],
    where: { menu: "Cuentas por pagar → Pagar" },
    hrefs: [
      { kind: "company", path: "/finanzas/cuentas-por-pagar", label: "CxP empresa" },
      { kind: "project", suffix: "/cuentas-por-pagar", label: "CxP de obra" },
    ],
    steps: [
      "Abrí la CxP → Registrar pago / Pagar.",
      "Cuenta, fecha, monto (click en el saldo para autocompletar; no reescribas «a ojo»).",
      "Método de liquidación y referencia opcionales.",
      "Confirmá. Bloquea si fondos insuficientes o período cerrado.",
    ],
    effects: ["Pagado (o parcial) + movimiento OUTFLOW + asiento DRAFT."],
    relatedSlugs: [
      "circuito-comprar-material-hasta-pagarlo",
      "por-que-un-pago-se-bloquea",
      "contabilizar-asientos",
    ],
    keywords: [
      "pagar",
      "cxp",
      "cuenta por pagar",
      "pago proveedor",
      "cuenta corriente",
      "saldar",
    ],
    guideRef: "§12.2",
  },
  {
    slug: "tablero-finanzas-tendencia",
    title: "Leer la tendencia de ingresos vs gastos",
    summary:
      "En el tablero de Finanzas (empresa u obra) el gráfico Tendencia mensual muestra ingresos vs gastos. Elegí Este mes, 3, 6 o 12 meses.",
    intents: ["tablero-finanzas"],
    modules: ["finanzas"],
    level: "both",
    typicalRoles: ["OWNER / ADMIN", "Finanzas", "PM"],
    permissionHint: "Company finance para /finanzas; en obra, permiso de finanzas del proyecto.",
    where: { menu: "Finanzas → Tablero · o Finanzas del proyecto → Tablero de finanzas" },
    hrefs: [
      { kind: "company", path: "/finanzas", label: "Tablero de finanzas (empresa)" },
      { kind: "project", suffix: "/finanzas", label: "Tablero de finanzas (obra)" },
    ],
    steps: [
      "Empresa: Finanzas → Tablero. Después de Indicadores está Tendencia mensual (todo el ancho).",
      "Obra: Finanzas del proyecto → Tablero de finanzas. El mismo gráfico va después de la visión rápida del mes.",
      "Rango: Este mes · 3 meses · 6 meses · 12 meses (queda en la URL como ?months=).",
      "En empresa, Económico es ingresos vs gastos; Caja es tesorería. Contabilidad se abre desde el menú Contabilidad, no desde el tablero.",
    ],
    effects: [
      "El rango filtra el gráfico. En la obra, la visión rápida del mes es el mes calendario actual (no el último punto del rango).",
    ],
    relatedSlugs: ["cobrar-una-cxc-de-obra", "montos-y-decimales"],
    keywords: [
      "tendencia mensual",
      "ingresos vs gastos",
      "tablero finanzas",
      "grafico finanzas",
      "este mes",
      "3 meses",
      "6 meses",
      "12 meses",
    ],
    guideRef: "§14",
  },
  {
    slug: "descuento-porcentual-en-lineas",
    title: "Descuento % en líneas (OC, cotización, factura)",
    summary:
      "Desc. % por línea, antes de IVA. Descuento general % copia el mismo porcentaje a todas las líneas.",
    intents: ["gasto-obra", "gasto-corporativo", "orden-compra", "montos-decimales"],
    modules: ["finanzas", "compras"],
    level: "both",
    typicalRoles: ["Administración", "Finanzas", "Compras", "PM"],
    where: { menu: "Líneas de OC, cotización, factura de gasto o factura de venta" },
    hrefs: [
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
    ],
    steps: [
      "En cada línea cargá Precio unit. (lista) y, si aplica, Desc. % (0 a 100).",
      "Para el mismo % en todas: escribí Descuento general % (0 a 100) → Aplicar a todas. Vacío no copia ni limpia.",
      "El descuento baja el subtotal; el IVA se calcula sobre el restante. El precio de lista no se pisa.",
      "En Factura B con precio c/IVA, el % se aplica al neto extraído, no al bruto.",
      "Guardá en borrador (100% en una línea está permitido). Emitir o confirmar la OC exige total mayor a cero.",
    ],
    effects: [
      "Subtotal e IVA bajan. El % se copia de cotización → OC y de OC → factura.",
      "La varianza vs APU y el saldo de partida usan el precio efectivo (con descuento).",
    ],
    pitfalls: [
      "No hay descuento en pesos de cabecera ni en recepciones/subcontratos.",
      "Si el documento queda en $0 no se puede emitir ni confirmar.",
    ],
    relatedSlugs: [
      "orden-de-compra-y-afectar-edt",
      "solicitud-de-compra",
      "gasto-de-obra-sin-oc",
      "gasto-corporativo",
      "montos-y-decimales",
    ],
    keywords: [
      "descuento",
      "descuento porcentual",
      "desc %",
      "descuento general",
      "bonificacion",
      "rebaja",
      "iva sobre descuento",
    ],
    guideRef: "§9.1 · §9.2 · §12.1 · §12.2 · D-093",
  },
];
