import type { HelpArticle } from "../types";

export const SUBCONTRACT_AR_ARTICLES: HelpArticle[] = [
  {
    slug: "crear-un-subcontrato",
    title: "Crear un subcontrato",
    summary: "Paquete de ejecución con subcontratista del Directorio. No es una OC.",
    intents: ["subcontrato"],
    modules: ["subcontratos"],
    level: "project",
    typicalRoles: ["PM", "Compras", "Administración"],
    where: { menu: "Finanzas del proyecto → Subcontratos" },
    hrefs: [{ kind: "project", suffix: "/subcontratos", label: "Subcontratos" }],
    steps: [
      "Prerrequisito: contacto con rol Subcontratista.",
      "Finanzas del proyecto → Subcontratos → Nuevo.",
      "Alcance e imputación a partidas (categoría SUB en APU cuando corresponda).",
    ],
    relatedSlugs: ["cargar-un-subcontratista", "certificar-y-pagar-subcontrato"],
    keywords: ["subcontrato", "crear subcontrato", "paquete"],
    guideRef: "§10",
  },
  {
    slug: "certificar-y-pagar-subcontrato",
    title: "Certificar y pagar un subcontrato",
    summary: "Certificación APPROVED → factura AP borrador → emitir → CxP → pago.",
    intents: ["certificar-subcontrato", "pagar-cxp"],
    modules: ["subcontratos", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas"],
    where: { menu: "Finanzas del proyecto → Subcontratos" },
    hrefs: [
      { kind: "project", suffix: "/subcontratos", label: "Subcontratos" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
    ],
    steps: [
      "Creá certificación de subcontrato del período.",
      "Emitir → Aprobar (o rechazar).",
      "Al aprobar: CTA a factura de proveedor en borrador (payee = subcontratista).",
      "Emití la factura → CxP → Pagá.",
    ],
    pitfalls: ["No pagues el subcontrato creando una OC ni eligiendo al subcontratista en el gasto genérico."],
    relatedSlugs: ["crear-un-subcontrato", "pagar-una-cuenta-por-pagar"],
    keywords: ["certificar subcontrato", "pagar subcontrato", "certificacion sub"],
    guideRef: "§10",
  },
  {
    slug: "emitir-y-aprobar-certificacion",
    title: "Emitir y aprobar certificación al cliente",
    summary: "Avance certificado sobre presupuesto APPROVED/CLOSED.",
    intents: ["certificacion-cliente"],
    modules: ["certificaciones"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Operación → Certificaciones" },
    hrefs: [{ kind: "project", suffix: "/certificaciones", label: "Certificaciones" }],
    steps: [
      "Prerrequisito: presupuesto APPROVED o CLOSED.",
      "Nueva certificación con período.",
      "Cargá Δ% físico y/o $ económico por partida.",
      "Emitir (ISSUED, inmutable) → Aprobar (APPROVED) o rechazar según el mandante.",
    ],
    relatedSlugs: ["facturar-una-certificacion", "aprobar-el-presupuesto"],
    keywords: ["certificacion", "certificar", "avance cliente", "certificado de avance", "certificado"],
    guideRef: "§11",
  },
  {
    slug: "facturar-una-certificacion",
    title: "Facturar una certificación",
    summary: "Desde certificación APPROVED → factura de venta → CxC.",
    intents: ["facturar-certificacion"],
    modules: ["certificaciones", "finanzas"],
    level: "project",
    typicalRoles: ["PM", "Finanzas", "Administración"],
    where: { menu: "Operación → Certificaciones / Facturas emitidas" },
    hrefs: [
      { kind: "project", suffix: "/certificaciones", label: "Certificaciones" },
      { kind: "project", suffix: "/facturas", label: "Facturas emitidas" },
    ],
    steps: [
      "En el detalle de la certificación APPROVED: CTA Emitir factura.",
      "Emití la factura de venta → genera Cuenta por cobrar.",
      "Cobrás desde CxC del proyecto (no hay Cobrar ahora al crear factura de obra).",
    ],
    relatedSlugs: ["cobrar-una-cxc-de-obra", "emitir-y-aprobar-certificacion"],
    keywords: ["facturar certificacion", "factura venta", "emitir factura"],
    guideRef: "§11.3 · §12.1",
  },
  {
    slug: "cobrar-una-cxc-de-obra",
    title: "Cobrar una CxC de obra",
    summary: "Cobranza confirmada acredita tesorería (INFLOW).",
    intents: ["cobrar"],
    modules: ["finanzas", "tesoreria"],
    level: "project",
    typicalRoles: ["Finanzas", "Administración", "Tesorería"],
    where: { menu: "Finanzas del proyecto → Cuentas por cobrar → Cobrar" },
    hrefs: [{ kind: "project", suffix: "/cuentas-por-cobrar", label: "Cuentas por cobrar" }],
    steps: [
      "CxC del proyecto → detalle → Cobrar.",
      "Cuenta, fecha, monto (2 decimales; usá el saldo que muestra el sistema), método y referencia.",
      "Confirmá. Solo la cobranza confirmada mueve caja.",
    ],
    relatedSlugs: ["facturar-una-certificacion", "ingreso-corporativo-con-factura"],
    keywords: [
      "cobrar",
      "cobranza",
      "cxc",
      "cuenta por cobrar",
      "cobrar factura",
      "cuenta corriente",
    ],
    guideRef: "§12.1",
  },
  {
    slug: "anticipo-o-venta-rapida",
    title: "Anticipo / venta rápida de obra",
    summary: "Factura + CxC (+ cobro opcional) en un paso desde la obra.",
    intents: ["anticipo", "cobrar"],
    modules: ["finanzas", "certificaciones"],
    level: "project",
    typicalRoles: ["Finanzas", "Administración", "PM"],
    where: { menu: "Finanzas del proyecto → Facturas emitidas → Anticipo" },
    hrefs: [{ kind: "project", suffix: "/facturas/anticipo/nueva", label: "Nuevo anticipo" }],
    steps: [
      "Entrá a la obra → Facturas emitidas.",
      "Alta de anticipo / venta rápida (`/facturas/anticipo/nueva`).",
      "Completá cliente/líneas; cobro opcional si tenés permiso de tesorería.",
      "Para facturar una certificación aprobada usá el CTA Emitir factura (otro flujo).",
    ],
    relatedSlugs: ["facturar-una-certificacion", "cobrar-una-cxc-de-obra"],
    keywords: ["anticipo", "venta rapida", "adelanto", "factura anticipo"],
    guideRef: "§12.1",
  },
  {
    slug: "ingreso-corporativo-con-factura",
    title: "Ingreso corporativo con factura",
    summary: "Ventas sin obra (capacitaciones, materiales de estructura) con CxC.",
    intents: ["ingreso-corporativo"],
    modules: ["finanzas"],
    level: "company",
    typicalRoles: ["Finanzas", "Administración"],
    permissionHint: "Rol de company finance.",
    where: { menu: "Finanzas → Transacciones → Ingreso / cobro" },
    hrefs: [{ kind: "company", path: "/finanzas/transacciones", label: "Transacciones" }],
    steps: [
      "Finanzas → Transacciones → Registrar → tab Ingreso / cobro.",
      "Modo Factura / cuenta por cobrar: cliente, líneas, vencimiento.",
      "Opcional: Cobrar ahora (ingreso a caja) si tenés permiso de tesorería.",
    ],
    relatedSlugs: ["ingreso-solo-caja", "cobrar-una-cxc-de-obra"],
    keywords: ["ingreso corporativo", "factura sin obra", "ar income"],
    guideRef: "§12.1",
  },
  {
    slug: "ingreso-solo-caja",
    title: "Ingreso solo caja (sin CxC)",
    summary: "Aportes, préstamos recibidos, devoluciones a la empresa. No es un reintegro a empleado.",
    intents: ["ingreso-solo-caja"],
    modules: ["finanzas", "tesoreria"],
    level: "company",
    typicalRoles: ["Finanzas", "Tesorería"],
    where: { menu: "Finanzas → Transacciones → Ingreso / cobro → Solo caja" },
    hrefs: [{ kind: "company", path: "/finanzas/transacciones", label: "Transacciones" }],
    steps: [
      "Transacciones → Ingreso / cobro → modo Solo caja (TREASURY_INFLOW).",
      "Cuenta, monto y fecha.",
    ],
    pitfalls: [
      "Reintegrar a un empleado es un EGRESO (Gasto / factura), no un ingreso Solo caja.",
    ],
    relatedSlugs: ["reintegrar-gasto-a-empleado", "ingreso-corporativo-con-factura"],
    keywords: ["solo caja", "aporte", "prestamo", "treasury inflow"],
    guideRef: "§12.1 · §17",
  },
];

export const AP_ARTICLES: HelpArticle[] = [
  {
    slug: "pagar-un-sueldo",
    title: "Pagar un sueldo (registro de costo)",
    summary:
      "Bloqer no liquida nómina ni aportes. Se registra el egreso como gasto ligado al empleado.",
    intents: ["pagar-sueldo"],
    modules: ["finanzas", "directorio"],
    level: "company",
    typicalRoles: ["Administración", "Finanzas"],
    permissionHint: "Company finance + Directorio para el empleado.",
    where: { menu: "Finanzas → Transacciones → Gasto / factura" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "company", path: "/directorio/nuevo?role=EMPLOYEE", label: "Alta de empleado" },
    ],
    steps: [
      "Directorio: el contacto existe con rol Empleado (activo).",
      "Finanzas → Transacciones → Registrar → tab Gasto / factura.",
      "A quién se le paga: elegí al empleado (figura «Nombre · Empleado»).",
      "Líneas / monto. Opcional: Pagar ahora (egreso de caja).",
      "Emití / pagá según el flujo.",
    ],
    effects: ["CxP + egreso si pagás; mapeado al empleado para reportes."],
    pitfalls: [
      "No marques al empleado como Proveedor solo para pagarle.",
      "No uses Solo caja (ingreso) para «pagar» un sueldo.",
    ],
    relatedSlugs: [
      "cargar-un-empleado",
      "reintegrar-gasto-a-empleado",
      "proveedor-empleado-o-subcontratista",
    ],
    keywords: [
      "sueldo",
      "sueldos",
      "pagar sueldo",
      "nomina",
      "haberes",
      "salario",
      "empleado",
      "liquidacion",
      "liquidacion de sueldos",
    ],
    guideRef: "§12.2.1",
  },
  {
    slug: "reintegrar-gasto-a-empleado",
    title: "Reintegrar un gasto a un empleado",
    summary: "El empleado adelantó plata; la empresa se la devuelve (egreso, no Solo caja).",
    intents: ["reintegro"],
    modules: ["finanzas", "directorio"],
    level: "both",
    typicalRoles: ["Administración", "Finanzas", "PM"],
    where: { menu: "Transacciones / Facturas proveedor (obra)" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones (empresa)" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor (obra)" },
    ],
    steps: [
      "Empleado en Directorio con rol Empleado.",
      "Empresa: Transacciones → Gasto / factura → payee = empleado → Pagar ahora.",
      "Obra: Facturas proveedor del proyecto, sin OC, líneas con partida EDT, payee = empleado.",
    ],
    pitfalls: [
      "No uses Solo caja (ingreso) para reintegrar.",
      "Si el «empleado» es monotributista y te pasa factura C: cargalo como Proveedor.",
    ],
    relatedSlugs: ["pagar-un-sueldo", "gasto-de-obra-sin-oc", "ingreso-solo-caja"],
    keywords: ["reintegro", "reembolsar", "adelanto", "combustible", "ferreteria"],
    guideRef: "§12.2.2",
  },
  {
    slug: "gasto-de-obra-sin-oc",
    title: "Gasto de obra sin OC",
    summary: "Factura de proveedor de proyecto con partida EDT obligatoria (sin orden de compra).",
    intents: ["gasto-obra"],
    modules: ["finanzas", "compras"],
    level: "project",
    typicalRoles: ["PM", "Administración", "Finanzas"],
    where: { menu: "Finanzas del proyecto → Facturas proveedor → Nueva" },
    hrefs: [{ kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" }],
    steps: [
      "Facturas proveedor → Nueva.",
      "A quién se le paga: Proveedor o Empleado.",
      "Cada línea con partida EDT obligatoria. Sin OC (o OC solo si el payee es el proveedor de esa OC).",
      "Crear → Emitir (o Emitir y pagar ahora).",
    ],
    relatedSlugs: ["reintegrar-gasto-a-empleado", "circuito-comprar-material-hasta-pagarlo"],
    keywords: ["gasto obra", "sin oc", "factura chica", "partida edt", "boleta", "factura proveedor"],
    guideRef: "§12.2",
  },
  {
    slug: "gasto-corporativo",
    title: "Gasto corporativo / factura de estructura",
    summary: "Gasto sin proyecto: alquiler, servicios, estructura.",
    intents: ["gasto-corporativo"],
    modules: ["finanzas"],
    level: "company",
    typicalRoles: ["Administración", "Finanzas"],
    where: { menu: "Finanzas → Facturas y gastos / Transacciones" },
    hrefs: [
      { kind: "company", path: "/finanzas/facturas-proveedor", label: "Facturas y gastos" },
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
    ],
    steps: [
      "Facturas y gastos → Nueva factura de gasto (sin proyecto), o Transacciones → Gasto / factura.",
      "A quién se le paga: proveedor o empleado (no Cliente). Buscá por nombre fantasía o razón social.",
      "Opcional: Pagar ahora.",
    ],
    pitfalls: [
      "Si el contacto está en Directorio y no aparece, no tiene rol Proveedor o Empleado activo: asignalo en su ficha.",
    ],
    relatedSlugs: ["pagar-un-sueldo", "pagar-una-cuenta-por-pagar"],
    keywords: ["gasto corporativo", "estructura", "alquiler", "factura gasto", "no aparece proveedor", "no aparece en facturas"],
    guideRef: "§12.2 · §14",
  },
  {
    slug: "emitir-y-pagar-ahora",
    title: "Emitir y pagar ahora",
    summary: "Factura emitida + CxP + pago + egreso en un paso (requiere permiso de tesorería).",
    intents: ["emitir-y-pagar"],
    modules: ["finanzas", "tesoreria"],
    level: "both",
    typicalRoles: ["Finanzas", "Tesorería", "Administración"],
    where: { menu: "Factura proveedor / Transacciones" },
    hrefs: [
      { kind: "company", path: "/finanzas/transacciones", label: "Transacciones" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor (obra)" },
    ],
    steps: [
      "Al crear/emitir, activá Emitir y pagar ahora (egreso de caja) / Pagar ahora.",
      "Elegí cuenta y fecha.",
      "Si no hay fondos suficientes, el sistema bloquea.",
    ],
    effects: ["Devengado + pagado + OUTFLOW; asientos DRAFT de factura y pago."],
    relatedSlugs: ["pagar-una-cuenta-por-pagar", "por-que-un-pago-se-bloquea"],
    keywords: ["emitir y pagar", "pagar ahora", "pago inmediato"],
    guideRef: "§12.2",
  },
  {
    slug: "pagar-una-cuenta-por-pagar",
    title: "Pagar una cuenta por pagar",
    summary: "Cadena Factura → Payable → Payment → OUTFLOW. Usá el saldo a 2 decimales.",
    intents: ["pagar-cxp"],
    modules: ["finanzas", "tesoreria"],
    level: "both",
    typicalRoles: ["Finanzas", "Tesorería", "Administración"],
    where: { menu: "Cuentas por pagar → Pagar" },
    hrefs: [
      { kind: "company", path: "/finanzas/cuentas-por-pagar", label: "CxP empresa" },
      { kind: "project", suffix: "/cuentas-por-pagar", label: "CxP de obra" },
    ],
    steps: [
      "Abrí la CxP → Registrar pago / Pagar.",
      "Cuenta, fecha, monto (click en el saldo para autocompletar; no reescribas «a ojo»).",
      "Método de liquidación y referencia opcionales.",
      "Confirmá. Bloquea si fondos insuficientes o período cerrado.",
    ],
    effects: ["Pagado (o parcial) + movimiento OUTFLOW + asiento DRAFT."],
    relatedSlugs: [
      "circuito-comprar-material-hasta-pagarlo",
      "por-que-un-pago-se-bloquea",
      "contabilizar-asientos",
    ],
    keywords: [
      "pagar",
      "cxp",
      "cuenta por pagar",
      "pago proveedor",
      "cuenta corriente",
      "saldar",
    ],
    guideRef: "§12.2",
  },
];
