import type { HelpArticle } from "../types";

export const PLANNING_ARTICLES: HelpArticle[] = [
  {
    slug: "armar-presupuesto-edt-apu",
    title: "Armar presupuesto, EDT y APU",
    summary: "Estructura de partidas (EDT) con análisis de precios unitarios por ítem.",
    intents: ["presupuesto-edt-apu"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["PM", "OWNER / ADMIN"],
    permissionHint: "Necesitás ver/editar Presupuestos en la obra.",
    where: { menu: "Planificación → Presupuesto" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Entrá a la obra → Planificación → Presupuesto.",
      "Armá la EDT (partidas hoja certificables).",
      "En cada partida, cargá el APU (insumos: materiales, mano de obra, etc.).",
      "Enviá a revisión y después Aprobá.",
    ],
    effects: ["Baseline para certificaciones y control de costos."],
    pitfalls: ["Los insumos (hierros, etc.) van en el APU, no como hijos EDT."],
    relatedSlugs: [
      "insumos-en-apu-no-hijos-edt",
      "aprobar-el-presupuesto",
      "editar-presupuesto-aprobado",
      "importar-cronograma",
    ],
    keywords: ["presupuesto", "edt", "apu", "wbs", "partidas"],
    guideRef: "§6",
  },
  {
    slug: "insumos-en-apu-no-hijos-edt",
    title: "Insumos van en el APU, no como hijos EDT",
    summary: "Evita partidas certificables falsas y doble multiplicación (D-057).",
    intents: ["presupuesto-edt-apu"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Planificación → Presupuesto → APU de la partida" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Abrí la partida hoja.",
      "Cargá materiales/MO/equipos en el APU de esa partida.",
      "No crees nodos hijos EDT solo para insumos.",
    ],
    relatedSlugs: ["armar-presupuesto-edt-apu"],
    keywords: ["apu", "insumos", "hierro", "hijos edt", "d-057"],
    guideRef: "§6 · §17",
  },
  {
    slug: "aprobar-el-presupuesto",
    title: "Aprobar el presupuesto",
    summary: "Sin presupuesto APPROVED/CLOSED no podés certificar con normalidad.",
    intents: ["aprobar-presupuesto"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["OWNER / ADMIN", "PM (si tiene APPROVE)"],
    where: { menu: "Planificación → Presupuesto" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Completá EDT + APU (APU requerido para aprobar).",
      "Enviar a revisión → Aprobar.",
      "Queda un solo APPROVED por obra (salvo reglas de versión documentadas).",
    ],
    figure: {
      src: "/help/mapa-presupuesto-edt.png",
      alt: "Bloqer — Presupuesto y EDT",
      caption: "Armar EDT + APU, enviar, aprobar o devolver. Insumos en el APU, no como hijos EDT.",
    },
    relatedSlugs: [
      "armar-presupuesto-edt-apu",
      "editar-presupuesto-aprobado",
      "emitir-y-aprobar-certificacion",
      "crear-adenda-de-presupuesto",
    ],
    keywords: ["aprobar presupuesto", "enviar a revision"],
    guideRef: "§6",
  },
  {
    slug: "editar-presupuesto-aprobado",
    title: "Editar un presupuesto ya aprobado",
    summary:
      "Excepción de OWNER/ADMIN: con la política encendida se puede cambiar partidas, APU, costos y venta. Por defecto está apagada.",
    intents: ["aprobar-presupuesto", "presupuesto-edt-apu"],
    modules: ["presupuesto", "configuracion"],
    level: "both",
    typicalRoles: ["OWNER / ADMIN"],
    permissionHint: "Encender/apagar: solo OWNER o ADMIN. Editar con la excepción activa: permiso de editar presupuestos.",
    where: { menu: "Configuración → Políticas → Presupuestos" },
    hrefs: [
      { kind: "company", path: "/configuracion/politicas#presupuestos", label: "Políticas" },
      { kind: "project", suffix: "/presupuestos", label: "Presupuesto" },
    ],
    steps: [
      "Por defecto un presupuesto Aprobado no se edita (ni partidas ni economía). Eso es lo correcto.",
      "OWNER o ADMIN: Configuración → Políticas → Presupuestos → Habilitar el interruptor de la organización.",
      "En la misma pantalla, Habilitar la obra que tenga el presupuesto aprobado.",
      "Quien tenga permiso de editar presupuestos puede agregar, quitar o cambiar partidas, APU, costos y venta.",
      "Cuando la obra esté definida, Congelar en la obra o Deshabilitar el interruptor de la organización.",
    ],
    effects: [
      "Cada cambio queda en el registro de actividad.",
      "Un presupuesto Cerrado nunca entra en esta excepción: ahí se usa adenda.",
    ],
    pitfalls: [
      "Hace falta el interruptor de la organización y el de la obra (los dos).",
      "No se pueden borrar partidas que ya estén usadas en certificaciones, OC, cronograma u otros documentos.",
      "Si el cronograma se armó desde este presupuesto, revisá el cronograma después de agregar o quitar partidas.",
    ],
    relatedSlugs: ["aprobar-el-presupuesto", "crear-adenda-de-presupuesto", "politicas-de-compras"],
    keywords: [
      "editar presupuesto aprobado",
      "excepcion presupuesto",
      "descongelar presupuesto",
      "agregar partidas aprobado",
      "politica presupuestos",
    ],
    guideRef: "§6.2",
  },
  {
    slug: "importar-cronograma",
    title: "Importar cronograma desde presupuesto",
    summary: "Alineá el plan temporal a la EDT.",
    intents: ["cronograma"],
    modules: ["cronograma", "presupuesto"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Planificación → Cronograma" },
    hrefs: [{ kind: "project", suffix: "/cronograma", label: "Cronograma" }],
    steps: [
      "Planificación → Cronograma → Importar desde presupuesto.",
      "Completá fechas en las hojas (no edites fechas de contenedores a mano: se pisan con el rollup).",
      "Agregá dependencias FS donde haga falta.",
    ],
    relatedSlugs: [
      "aprobar-el-presupuesto",
      "cargar-libro-de-obra",
      "cuatro-dimensiones-de-avance",
      "agregar-hito-al-cronograma",
      "exportar-cronograma",
    ],
    keywords: ["cronograma", "gantt", "importar", "fechas"],
    guideRef: "§7",
  },
  {
    slug: "agregar-hito-al-cronograma",
    title: "Agregar un hito o tarea al cronograma",
    summary: "Ubicá el ítem a la altura correcta; el vínculo EDT no mueve la fila.",
    intents: ["cronograma"],
    modules: ["cronograma"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Planificación → Cronograma → + Tarea / hito" },
    hrefs: [{ kind: "project", suffix: "/cronograma", label: "Cronograma" }],
    steps: [
      "Cronograma → + Tarea / hito. Elegí tipo Tarea o Hito y las fechas.",
      "En Ubicación: Colocar bajo (capítulo o raíz) e Insertar después de (hermano).",
      "Si vinculás una partida EDT que ya tiene una tarea hoja, el sistema propone poner el nuevo ítem justo debajo (hermano, no hijo).",
      "Después podés reordenar con el botón ⋮ de la fila (Gantt, tabla o detalle). En el Gantt el chip Sin EDT va junto al nombre; días, ⋮ y FS quedan alineados a la derecha.",
      "Filtrá Tipo = Hitos para ver solo diamantes. Los hitos no toman % Real del libro de obra.",
      "Al confirmar una recepción de OC con la misma EDT, el hito Planificado/En curso pasa a Completado automáticamente.",
    ],
    effects: [
      "El ítem queda en el árbol (padre + orden) independiente del vínculo EDT.",
      "Hito con color fijo en el Gantt; recepción confirmada completa el hito vinculado ([D-104]).",
    ],
    pitfalls: [
      "No anides un hito debajo de la tarea de montaje: esa tarea pasaría a contenedor y perdería fechas editables.",
      "El vínculo EDT alimenta costos y (en tareas) el % Real; no cambia la altura en el Gantt.",
      "Anular la recepción no reabre el hito: si hace falta, reabrilo a mano desde el detalle.",
    ],
    relatedSlugs: ["importar-cronograma", "cuatro-dimensiones-de-avance", "cargar-libro-de-obra", "recibir-una-oc", "exportar-cronograma"],
    keywords: [
      "hito",
      "milestone",
      "orden",
      "llegada",
      "paneles",
      "cronograma",
      "ubicación",
      "recepción",
      "entrega oc",
      "sangrar",
      "ir a hoy",
    ],
    guideRef: "§7",
  },
  {
    slug: "exportar-cronograma",
    title: "Exportar el cronograma a PDF o Excel",
    summary: "Bajá tabla, Gantt o ambos, con un lapso opcional y los filtros de la pantalla.",
    intents: ["cronograma", "exportar-reportes"],
    modules: ["cronograma"],
    level: "project",
    typicalRoles: ["PM", "OWNER / ADMIN"],
    permissionHint: "Necesitás ver Cronograma.",
    where: { menu: "Planificación → Cronograma → Exportar" },
    hrefs: [{ kind: "project", suffix: "/cronograma", label: "Cronograma" }],
    steps: [
      "Entrá a la obra → Planificación → Cronograma (vista escritorio).",
      "Aplicá los filtros que quieras (tipo, estado, solo atrasados, presupuesto). La Leyenda de avances está en esa misma barra.",
      "Pulsá Exportar: elegí Tabla, Gantt o Ambos, y un lapso (Desde/Hasta o atajos Todo / Este mes / Este trimestre / Este año). Después Excel o PDF.",
      "El PDF es apaisado y se parte en páginas según el contenido: tabla de fechas, tabla de avance/costos, y/o Gantt (el eje largo sigue en hojas siguientes). Cada página lleva empresa y obra.",
      "El Excel trae hoja Tabla (fechas dd/mm/aaaa) y/o hoja Gantt con celdas del mismo color que las barras.",
    ],
    effects: [
      "Se descarga un archivo con los ítems visibles según el filtro y el lapso (incluye capítulos padre; las canceladas siguen ocultas salvo que filtres Cancelado).",
    ],
    pitfalls: [
      "En el celular no está el botón: usá escritorio o una ventana ancha.",
      "Sin lapso, el Gantt usa el rango de fechas de los ítems filtrados, no el zoom de la pantalla.",
      "Con Desde/Hasta, un ítem sin fechas no entra salvo que sea capítulo padre de uno que sí se solapa.",
    ],
    relatedSlugs: ["importar-cronograma", "agregar-hito-al-cronograma", "exportar-reportes-csv-pdf"],
    keywords: [
      "exportar cronograma",
      "cronograma pdf",
      "cronograma excel",
      "gantt pdf",
      "descargar gantt",
      "imprimir cronograma",
      "xlsx cronograma",
      "exportar lapso",
      "exportar tabla",
    ],
    guideRef: "§7",
  },
  {
    slug: "cargar-libro-de-obra",
    title: "Cargar el parte de libro de obra",
    summary: "Avance real diario; al aprobar alimenta el cronograma.",
    intents: ["libro-obra"],
    modules: ["libro-obra"],
    level: "project",
    typicalRoles: ["Capataz", "PM"],
    where: { menu: "Operación → Libro de obra" },
    hrefs: [{ kind: "project", suffix: "/libro-obra", label: "Libro de obra" }],
    steps: [
      "Operación → Libro de obra → nuevo parte.",
      "Clima, cuadrilla, fotos. En Notas generales: viñetas, numeración o negrita para listar tareas o problemas. En avance: agregá una fila, elegí la partida EDT (% del día restante y cantidad se precargan). Si cambiás el % o la cantidad, el otro campo se alinea al presupuesto de la partida. En mano de obra, buscá el contacto por razón social o nombre fantasía.",
      "Enviar (SUBMITTED): el PM del Equipo de obra (y OWNER/ADMIN) reciben campana + email.",
      "Si te lo devuelven, corregí desde el enlace de la notificación.",
      "Desde el detalle: Exportar PDF (incluye fotos jpeg/png/webp si hay adjuntos).",
    ],
    effects: [
      "Al aprobar: avance real del cronograma (+ consumo stock si aplica).",
      "Al aprobar/devolver: el autor recibe campana + email.",
      "OWNER/ADMIN pueden programar el parte del día por email (empresa → Reportes programados).",
    ],
    pitfalls: [
      "Cada fila de avance necesita partida EDT y cantidad. Si falta alguno, el parte no se guarda.",
      "El % avance libro de EDT y costos solo suma partes APPROVED. Mientras el parte esté enviado (SUBMITTED) no mueve esa columna. La vista Financiero no muestra %: cambiá a Cantidades o % Avance.",
      "En materiales, descripción y cantidad son obligatorios: una fila a medias no se graba.",
      "Fotos HEIC de iPhone no se embeben en el PDF; conviene jpeg/png/webp.",
    ],
    relatedSlugs: [
      "registrar-consumo-materiales",
      "asignar-equipo-de-obra",
      "usar-notificaciones",
      "revisar-pendientes",
      "programar-envios-de-reportes",
      "exportar-reportes-csv-pdf",
      "ver-y-descargar-documento",
    ],
    keywords: [
      "libro de obra",
      "parte diario",
      "capataz",
      "avance",
      "parte pendiente",
      "avance de obra",
      "exportar parte",
      "fotos parte",
      "notas generales",
      "viñetas",
      "numeración",
      "lista",
    ],
    guideRef: "§8.1",
  },
  {
    slug: "ver-y-descargar-documento",
    title: "Ver y descargar un documento",
    summary: "En Documentos, las acciones son iconos: ojo para abrir y flecha para bajar el archivo.",
    intents: ["documentos-obra"],
    modules: ["general"],
    level: "project",
    typicalRoles: ["PM", "Administración", "Capataz"],
    where: { menu: "Operación → Documentos" },
    hrefs: [{ kind: "project", suffix: "/documentos", label: "Documentos" }],
    steps: [
      "Operación → Documentos.",
      "En la columna Acciones: el icono de ojo abre el archivo en una pestaña nueva (PDF e imágenes); el icono de descarga baja el archivo.",
      "El nombre del archivo abre el detalle (ficha, archivar o eliminar).",
      "Los mismos iconos están en las tarjetas y en los adjuntos de un parte, OC o factura.",
    ],
    pitfalls: [
      "Si ves un icono de archivo tachado, no hay binario almacenado (almacenamiento no configurado al subir).",
      "HEIC de iPhone no siempre se puede previsualizar: usá descargar.",
    ],
    relatedSlugs: ["cargar-libro-de-obra"],
    keywords: [
      "documentos",
      "ver documento",
      "descargar",
      "icono ojo",
      "icono descarga",
      "biblioteca",
      "adjunto",
    ],
    guideRef: "§8.4",
  },
  {
    slug: "registrar-consumo-materiales",
    title: "Registrar consumo de materiales",
    summary: "Baja de stock imputada a partida cuando corresponde.",
    intents: ["consumo-materiales"],
    modules: ["materiales", "inventario"],
    level: "project",
    typicalRoles: ["Capataz", "PM", "Depósito"],
    where: { menu: "Operación → Consumos" },
    hrefs: [{ kind: "project", suffix: "/consumos", label: "Consumos" }],
    steps: [
      "Operación → Consumos (o el atajo Consumos en Materiales, o desde el flujo de libro de obra).",
      "Indicá material, cantidad y partida EDT si el parte toca varias partidas.",
    ],
    relatedSlugs: ["cargar-libro-de-obra", "pedir-material-desde-faltante", "tablero-materiales"],
    keywords: ["consumo", "consumos", "stock", "materiales"],
    guideRef: "§8",
  },
  {
    slug: "tablero-materiales",
    title: "Tablero de materiales",
    summary:
      "Cantidades APU vs pedido, recibido y consumido. Operativo y Varianza ($) en una fila; atajos a EDT, compras y consumos.",
    intents: ["pedir-material"],
    modules: ["materiales", "compras"],
    level: "project",
    typicalRoles: ["PM", "Compras", "Capataz"],
    where: { menu: "Operación → Materiales" },
    hrefs: [
      { kind: "project", suffix: "/materiales", label: "Materiales" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
      { kind: "project", suffix: "/control-costos", label: "EDT y costos" },
      { kind: "project", suffix: "/consumos", label: "Consumos" },
    ],
    steps: [
      "Operación → Materiales.",
      "En escritorio: a la izquierda Operativo / Varianza ($); a la derecha EDT y costos, Tablero de compras y Consumos (Exportar solo en Varianza).",
      "Operativo es cantidades (faltante → Pedir). Varianza ($) es desvío de $ vs consumo de stock.",
      "Para ver o crear solicitudes, entrá a Tablero de compras (Nueva solicitud / Todas las solicitudes). No hay atajo Solicitudes en Materiales.",
      "En celular o tablet chica: tarjetas de necesidad/faltante (sin Operativo/Varianza). Los mismos atajos quedan en una franja que se desplaza de costado; las etiquetas se acortan (EDT, Compras).",
    ],
    pitfalls: [
      "Materiales no reemplaza EDT y costos: acá son cantidades; el $ por partida está en Planificación → EDT y costos.",
    ],
    relatedSlugs: [
      "pedir-material-desde-faltante",
      "registrar-consumo-materiales",
      "circuito-comprar-material-hasta-pagarlo",
      "leer-edt-y-costos",
    ],
    keywords: [
      "tablero materiales",
      "materiales operativo",
      "varianza materiales",
      "atajos materiales",
    ],
    guideRef: "§9.0",
  },
];

export const PROCUREMENT_ARTICLES: HelpArticle[] = [
  {
    slug: "circuito-comprar-material-hasta-pagarlo",
    title: "Circuito: comprar material hasta pagarlo",
    summary:
      "El caminito: si esto, entonces aquello. SC o OC directa → aprobar o devolver → confirmar → recibir → facturar → pagar.",
    intents: ["comprar-material", "orden-compra", "pagar-cxp"],
    modules: ["compras", "materiales", "finanzas"],
    level: "project",
    typicalRoles: ["Compras", "PM", "Finanzas"],
    where: { menu: "Compras → Tablero / OC / Recepciones · Pendientes" },
    hrefs: [
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "company", path: "/pendientes", label: "Pendientes" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
      { kind: "project", suffix: "/cuentas-por-pagar", label: "Cuentas por pagar" },
    ],
    stepsTitle: "Caminito",
    steps: [
      "¿La política permite OC directa y el monto está bajo el umbral (o es emergencia OWNER)? Si sí → OC borrador. Si no → SC (EDT + fecha requerida) → Enviar → Cotizar → Elegir proveedor → OC borrador. Si está sobre el umbral y no es emergencia → Bloqer exige SC.",
      "¿Política «Un paso: autorizar y comprometer» ON? Bajo umbral → Autorizar y comprometer. Alto nivel → solo Admin ([D-106]). Si no → Enviar a aprobación.",
      "Camino clásico: si aprueban → Aprobada (todavía no reserva $), salvo política «Al aprobar, confirmar» ([D-107]) → botón **Aprobar y comprometer** y queda Confirmada. Si no aprueban → Devolver a borrador. Después (si hace falta): Confirmar al proveedor → Comprometido.",
      "¿Llegó mercadería? Si sí → Recepción (stock; no abre CxP). Con política [D-108] puede nacer borrador de factura. Panel Facturación arriba. Si el mes está cerrado → no se confirma, recibe ni factura.",
      "¿Hay cantidad recibida? Si sí → Completar/Emitir factura = Devengado + CxP. Si no → no hay factura desde esa OC.",
      "¿Hay fondos en la cuenta? Si sí → Pagar = Pagado + egreso. Si no → Bloqer bloquea el pago.",
    ],
    effects: [
      "Aprobada = control interno (todavía no reserva $).",
      "Confirmada → Comprometido en EDT.",
      "Recepción → stock (no abre CxP).",
      "Factura emitida → Devengado + CxP.",
      "Pago → Pagado + egreso de caja.",
    ],
    pitfalls: [
      "Subcontrato y reintegro no van por este circuito.",
      "Toda línea de obra imputa a una partida hoja EDT.",
      "Anular una OC que ya tiene recepciones o facturas: primero anular esos documentos.",
      "Pendientes es el portero: Cotizar → Aprobación → Confirmar → Recibir → Facturar.",
    ],
    figure: {
      src: "/help/mapa-flujo-compras-si-no.png",
      alt: "Bloqer — Compra: si esto, entonces aquello",
      caption:
        "El caminito: qué sigue si sí y qué pasa si no. La lámina con roles y detalle está en Ayuda → Mapas de proceso.",
    },
    relatedSlugs: [
      "pedir-material-desde-faltante",
      "tablero-materiales",
      "solicitud-de-compra",
      "orden-de-compra-y-afectar-edt",
      "recibir-una-oc",
      "factura-desde-oc",
      "pagar-una-cuenta-por-pagar",
      "anular-devolver-cancelar-documentos",
      "revisar-pendientes",
    ],
    keywords: [
      "comprar material",
      "compra",
      "procure to pay",
      "orden de compra",
      "aprobar orden de compra",
      "afectar edt",
      "cuenta por pagar",
      "hierro",
      "cemento",
      "mapa de compras",
      "circuito sc oc",
      "si no se autoriza",
      "caminito",
      "si esto entonces aquello",
      "flujo de compra",
      "autorizar y comprometer",
      "un paso",
      "pendientes",
      "portero",
    ],
    guideRef: "§9 · §12.2 · §16",
  },
  {
    slug: "pedir-material-desde-faltante",
    title: "Pedir material desde faltante",
    summary: "Tablero de cantidades: Pedir prellena una solicitud de compra con el faltante restante.",
    intents: ["pedir-material", "comprar-material"],
    modules: ["materiales", "compras"],
    level: "project",
    typicalRoles: ["PM", "Compras"],
    where: { menu: "Operación → Materiales" },
    hrefs: [
      { kind: "project", suffix: "/materiales", label: "Materiales" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
    ],
    steps: [
      "Operación → Materiales (vista Operativo; en la misma fila, a la derecha, están los atajos).",
      "En una fila con faltante, pulsá Pedir. La cantidad prellenada es el resto (necesidad − ya pedido).",
      "Si ya hay una SC u OC de esa línea, el botón dice Pedir resto y también podés abrir el documento.",
      "Para el listado de solicitudes: atajo Tablero de compras → Todas las solicitudes / Nueva solicitud.",
    ],
    pitfalls: [
      "$ Presup. es el total APU de la línea, no el saldo por comprar.",
      "Pedido no incluye OC en borrador ni aprobada sin confirmar.",
    ],
    relatedSlugs: ["tablero-materiales", "solicitud-de-compra", "circuito-comprar-material-hasta-pagarlo"],
    keywords: ["pedir", "faltante", "materiales", "necesidad"],
    guideRef: "§9.0",
  },
  {
    slug: "solicitud-de-compra",
    title: "Solicitud de compra",
    summary: "Pedido interno con partida EDT, cotizaciones y selección de proveedor.",
    intents: ["solicitud-compra"],
    modules: ["compras"],
    level: "project",
    typicalRoles: ["PM", "Compras"],
    where: { menu: "Compras → Solicitudes de compra" },
    hrefs: [
      { kind: "project", suffix: "/solicitudes-compra", label: "Solicitudes de compra" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
    ],
    steps: [
      "Nueva solicitud desde Compras → Solicitudes de compra o Tablero de compras (Nueva solicitud / Todas las solicitudes). También desde Materiales → Pedir.",
      "En el listado (desktop): Descripción, WBS, Monto est. (Presup. o Cotización), Proveedor y Necesaria para. El solicitante y las fechas están en el detalle.",
      "Arriba del listado tenés un buscador (código, descripción, WBS, proveedor, solicitante) y botones de estado (Todas / Borrador / Enviada / Cotización elegida / Completada / Anulada) con contador. Los deep-links históricos (?status=SUBMITTED) siguen abriendo el filtro pre-seleccionado.",
      "Líneas con cantidad, unidad, descripción y partida EDT obligatoria.",
      "Fecha requerida: obligatoria. Es cuándo se necesita el material en obra y aparece como Necesaria para en el listado y en Pendientes.",
      "Guardar DRAFT → Enviar (SUBMITTED). Quienes pueden cotizar la ven en Pendientes. La campana de nueva solicitud va a quien aprueba SC/OC (y OWNER/ADMIN), no necesariamente a todos los que cotizan.",
      "Cargar cotizaciones: elegí proveedor por razón social o nombre fantasía, precio unitario, Desc. % opcional (antes de IVA) y plazo según política. Después de guardar, cada cotización muestra el precio de lista y el Desc. % por línea. El umbral SC vs OC directa lo setea la empresa en políticas de compras.",
      "Seleccionar proveedor → genera OC en borrador.",
      "Si pasa la fecha requerida y la SC sigue Submitted o con cotización elegida sin OC confirmada, aparece un badge rojo Vencida N d junto a Necesaria para en el listado y en Pendientes. Se avisa por campana + email a compras/aprobadores todos los días hasta cerrar el ciclo (dedup 7 días; colchón y toggle en Configuración → Políticas de compras).",
    ],
    pitfalls: [
      "Sin fecha requerida no se puede guardar la SC. Cotizadores y compradores usan ese dato para priorizar.",
      "Si la SC vence sin OC, no bloquea nada, pero sigue apareciendo como alerta hasta cerrar el circuito.",
    ],
    relatedSlugs: [
      "tablero-materiales",
      "orden-de-compra-y-afectar-edt",
      "politicas-de-compras",
      "descuento-porcentual-en-lineas",
      "revisar-pendientes",
    ],
    keywords: [
      "solicitud",
      "sc",
      "cotizacion",
      "cotizar",
      "pedido",
      "pedido de compra",
      "solicitud de compra",
      "monto estimado",
      "proveedor seleccionado",
      "wbs",
      "espera cotizaciones",
      "pendientes compras",
      "buscar solicitudes",
      "filtro solicitudes",
      "buscar sc",
      "filtro sc",
      "fecha requerida",
      "necesaria para",
      "vencida",
      "vencimiento",
      "alerta",
      "recordatorio",
    ],
    guideRef: "§9.1",
  },
  {
    slug: "orden-de-compra-y-afectar-edt",
    title: "Orden de compra y afectar EDT",
    summary:
      "Confirmar al proveedor = Comprometido. Con política, OC bajo umbral puede Autorizar y comprometer en un paso.",
    intents: ["orden-compra", "comprar-material"],
    modules: ["compras", "presupuesto"],
    level: "project",
    typicalRoles: ["Compras", "PM", "OWNER / ADMIN"],
    where: { menu: "Compras → Órdenes de compra" },
    hrefs: [{ kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" }],
    steps: [
      "Nueva OC (dialog en escritorio; en celular `/ordenes-compra/nueva`) o desde SC seleccionada. Proveedor: buscá por razón social o nombre fantasía. Cada línea: partida hoja, **Tipo de costo** (Materiales / Mano de obra / Equipos / Subcontratos / Otros; **Sugerido desde APU**), unidad / cantidad / precio unitario / ref. presupuesto, y debajo Desc. % · IVA · total. Descuento general % + Aplicar a todas copia el mismo % (hay que ingresar un número; 0 limpia todas).",
      "En el listado de OC hay un buscador (código, proveedor, aprobador) y botones de estado (Todas / Borrador / Pend. aprobación / Aprobada / Confirmada / Recep. parcial / Recibida / Anulada) con contador por estado. Los deep-links históricos (?status=) siguen funcionando como filtro inicial (por ejemplo desde Pendientes).",
      "Ref. presupuesto muestra el insumo de materiales del APU, o el costo dir. /u de la partida si esa partida no tiene materiales (p. ej. solo mano de obra).",
      "Camino clásico: Enviar a aprobación → **Aprobar** (control interno; todavía no reserva $) o **Aprobar y comprometer** si la política «Al aprobar, confirmar» está ON ([D-107]), o Devolver a borrador con motivo. Si el precio supera el referencial, completá Justificación desvío. Comprar por debajo no pide nota. Aprobadores la ven en Pendientes (etapa Aprobación) + campana.",
      "Confirmar al proveedor → CONFIRMED = Comprometido en EDT y costos. Quien puede confirmar la ve en Pendientes; Depósito/Compras reciben campana al confirmar para registrar recepción.",
      "Atajo (política / Atajos operativos): **Un paso: autorizar y comprometer** — bajo umbral: PM/Compras; alto nivel: Admin ([D-106]). Si D-105 y D-107 están ON en Pend. aprobación, Autorizar es el botón primario.",
      "Si la OC queda Confirmada o Recep. parcial y pasa la Entrega prevista, aparece un badge rojo Vencida N d junto a Entrega prevista en el listado y en Pendientes.",
      "Al recibir: panel Facturación arriba. Con política [D-108] puede crearse borrador de factura automáticamente (emitir = CxP). Pendientes muestra **Registrar factura** o **Completar factura** hasta ISSUED.",
      "Luego recepción y factura (el tipo se hereda de la línea de OC).",
    ],
    effects: [
      "APPROVED = control interno (sin $), salvo auto-confirm ON. CONFIRMED = Comprometido. El atajo escribe ambos en un acto.",
    ],
    pitfalls: [
      "Sin política ON no hay botón de un paso: Enviar → Aprobar → Confirmar.",
      "Aprobar sola no compromete (salvo política Al aprobar, confirmar → botón **Aprobar y comprometer**).",
      "Alto nivel: solo Admin en el atajo de un paso; al aprobar no auto-confirma.",
      "Badge **Aprobada** (outline) ≠ **Confirmada** (primary / Comprometido).",
      "Si Ref. presup. sale — la partida no tiene APU ni costo dir. /u: hay que justificar el desvío o completar el presupuesto.",
      "Sin factura de proveedor emitida no hay CxP: borrador ≠ deuda.",
      "**Mano de obra externa** (cuadrilla contratada, empresa de albañilería, jornal facturado como AP): tipá la línea como **Mano de obra**. No hace falta contrato de subcontrato — SUB se usa solo con el módulo Subcontratos + certificación.",
      "**Alquiler de equipos** (baño químico, retro): al elegir la partida se pre-tipa como Equipos si el APU lo indica; verificalo antes de confirmar.",
    ],
    relatedSlugs: [
      "circuito-comprar-material-hasta-pagarlo",
      "recibir-una-oc",
      "leer-edt-y-costos",
      "anular-devolver-cancelar-documentos",
      "afectaciones-comprometido-devengado-pagado",
      "descuento-porcentual-en-lineas",
      "revisar-pendientes",
      "politicas-de-compras",
    ],
    keywords: [
      "orden de compra",
      "oc",
      "aprobar orden de compra",
      "aprobar oc",
      "aprobacion oc",
      "enviar a aprobacion",
      "confirmar",
      "pendiente de confirmar",
      "comprometido",
      "afectar edt",
      "ref presup",
      "valor referencial",
      "justificacion desvio",
      "desvio verde",
      "desvio rojo",
      "pendientes compras",
      "buscar orden de compra",
      "buscar oc",
      "filtro oc",
      "filtro orden de compra",
      "entrega prevista",
      "vencida",
      "vencimiento",
      "alerta entrega",
      "oc sin factura",
      "recibida sin factura",
      "registrar factura desde oc",
      "autorizar y comprometer",
      "un paso",
      "compromisos",
    ],
    guideRef: "§9.2 · [D-105]",
  },
  {
    slug: "recibir-una-oc",
    title: "Recibir una OC",
    summary: "Ingreso de stock. La recepción sola no crea cuenta por pagar.",
    intents: ["recepcion"],
    modules: ["compras", "inventario"],
    level: "project",
    typicalRoles: ["Compras", "Depósito"],
    where: { menu: "Compras → Recepciones (OC en Compras → Órdenes de compra)" },
    hrefs: [
      { kind: "project", suffix: "/recepciones", label: "Recepciones" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
    ],
    steps: [
      "Desde Pendientes (botón Recibir → abre …/recepciones/nueva), desde la campana al confirmar (CTA Registrar recepción), desde la OC (Compras → Órdenes de compra) o Compras → Recepciones.",
      "Registrá recepción parcial o total. El depósito es opcional si Inventario está activo.",
      "Al confirmar la recepción, el panel Facturación queda arriba. Si la política «Al recibir, crear borrador» está ON, ya hay borrador para Completar y emitir (no crea CxP sola la recepción).",
    ],
    effects: [
      "Stock + cantidades recibidas. No crea CxP sola.",
      "Con política [D-108]: borrador AP automático (idempotente).",
      "Si hay un hito del cronograma vinculado a la misma EDT (Planificado/En curso), queda Completado ([D-104]).",
    ],
    pitfalls: [
      "La recepción no abre deuda: hay que emitir la factura. Pedile a Finanzas o usá el panel si tenés EDIT AP.",
    ],
    relatedSlugs: [
      "factura-desde-oc",
      "orden-de-compra-y-afectar-edt",
      "revisar-pendientes",
      "agregar-hito-al-cronograma",
    ],
    keywords: [
      "recepcion",
      "recibir",
      "stock",
      "entrada",
      "remito",
      "ingresar mercaderia",
      "entrar mercaderia",
      "recibir oc",
      "pendiente de recepcion",
      "deposito",
      "pendientes compras",
      "hito",
      "cronograma",
    ],
    guideRef: "§9.3",
  },
  {
    slug: "factura-desde-oc",
    title: "Factura desde OC",
    summary: "Copia la partida EDT de cada línea. Al emitir: Devengado + CxP.",
    intents: ["factura-desde-oc"],
    modules: ["compras", "finanzas"],
    level: "project",
    typicalRoles: ["Compras", "Finanzas", "Administración"],
    where: { menu: "Facturas proveedor / desde OC" },
    hrefs: [
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
    ],
    steps: [
      "Desde Pendientes (**Registrar factura** o **Completar factura**) aterrizás en la OC / borrador; desde recepción confirmada u OC: panel Facturación → **Registrar factura**.",
      "Revisá montos, **Tipo de costo** (se hereda de la OC; ajustalo si hace falta) y adjunto del comprobante.",
      "Crear → borrador → Emitir (o Emitir y pagar ahora).",
      "**Sin OC**: al elegir la partida, el sistema pre-tipa la línea con la categoría dominante del APU (baño químico → EQP; excavación con retro → EQP). Si es mixto, queda Materiales con hint.",
    ],
    effects: ["Emitir → Devengado + CxP + asiento DRAFT (en el bucket del tipo de cada línea)."],
    pitfalls: [
      "Gasto directo sin OC: revisá el Tipo de costo sugerido. Cambialo si no aplica.",
      "**Mano de obra externa** (cuadrilla, empresa de albañilería, jornal facturado): tipá la línea como **Mano de obra**. No hace falta subcontrato; SUB es solo con módulo Subcontratos + certificación.",
      "**Alquiler de equipos** facturado por proveedor: tipá como **Equipos**.",
    ],
    relatedSlugs: [
      "pagar-una-cuenta-por-pagar",
      "emitir-y-pagar-ahora",
      "descuento-porcentual-en-lineas",
      "leer-edt-y-costos",
      "revisar-pendientes",
      "recibir-una-oc",
    ],
    keywords: [
      "factura desde oc",
      "traer lineas",
      "factura proveedor",
      "factura de compra",
      "boleta",
      "boleta de compra",
      "tipo de costo",
    ],
    guideRef: "§9.2 · §12.2 · [D-099]",
  },
  {
    slug: "oc-directa-vs-con-solicitud",
    title: "OC directa vs con solicitud",
    summary: "OC directa solo si la política de compras lo habilita.",
    intents: ["oc-directa", "orden-compra"],
    modules: ["compras", "configuracion"],
    level: "project",
    typicalRoles: ["Compras", "OWNER / ADMIN"],
    where: { menu: "Compras → Órdenes de compra / Configuración → Políticas" },
    hrefs: [
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "company", path: "/configuracion/politicas", label: "Políticas" },
    ],
    steps: [
      "Con SC: flujo completo de cotización y selección.",
      "OC directa: Nueva OC sin SC si la política lo permite; umbrales altos pueden exigir motivo de emergencia.",
    ],
    relatedSlugs: ["politicas-de-compras", "orden-de-compra-y-afectar-edt"],
    keywords: ["oc directa", "sin solicitud", "emergencia"],
    guideRef: "§9.2",
  },
];
