import type { HelpArticle } from "../types";

export const PLANNING_ARTICLES: HelpArticle[] = [
  {
    slug: "armar-presupuesto-edt-apu",
    title: "Armar presupuesto, EDT y APU",
    summary: "Estructura de partidas (EDT) con análisis de precios unitarios por ítem.",
    intents: ["presupuesto-edt-apu"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["PM", "OWNER / ADMIN"],
    permissionHint: "Necesitás ver/editar Presupuestos en la obra.",
    where: { menu: "Planificación → Presupuesto" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Entrá a la obra → Planificación → Presupuesto.",
      "Armá la EDT (partidas hoja certificables).",
      "En cada partida, cargá el APU (insumos: materiales, mano de obra, etc.).",
      "Enviá a revisión y después Aprobá.",
    ],
    effects: ["Baseline para certificaciones y control de costos."],
    pitfalls: ["Los insumos (hierros, etc.) van en el APU, no como hijos EDT."],
    relatedSlugs: ["insumos-en-apu-no-hijos-edt", "aprobar-el-presupuesto", "importar-cronograma"],
    keywords: ["presupuesto", "edt", "apu", "wbs", "partidas"],
    guideRef: "§6",
  },
  {
    slug: "insumos-en-apu-no-hijos-edt",
    title: "Insumos van en el APU, no como hijos EDT",
    summary: "Evita partidas certificables falsas y doble multiplicación (D-057).",
    intents: ["presupuesto-edt-apu"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Planificación → Presupuesto → APU de la partida" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Abrí la partida hoja.",
      "Cargá materiales/MO/equipos en el APU de esa partida.",
      "No crees nodos hijos EDT solo para insumos.",
    ],
    relatedSlugs: ["armar-presupuesto-edt-apu"],
    keywords: ["apu", "insumos", "hierro", "hijos edt", "d-057"],
    guideRef: "§6 · §17",
  },
  {
    slug: "aprobar-el-presupuesto",
    title: "Aprobar el presupuesto",
    summary: "Sin presupuesto APPROVED/CLOSED no podés certificar con normalidad.",
    intents: ["aprobar-presupuesto"],
    modules: ["presupuesto"],
    level: "project",
    typicalRoles: ["OWNER / ADMIN", "PM (si tiene APPROVE)"],
    where: { menu: "Planificación → Presupuesto" },
    hrefs: [{ kind: "project", suffix: "/presupuestos", label: "Presupuesto" }],
    steps: [
      "Completá EDT + APU (APU requerido para aprobar).",
      "Enviar a revisión → Aprobar.",
      "Queda un solo APPROVED por obra (salvo reglas de versión documentadas).",
    ],
    relatedSlugs: ["armar-presupuesto-edt-apu", "emitir-y-aprobar-certificacion", "crear-adenda-de-presupuesto"],
    keywords: ["aprobar presupuesto", "enviar a revision"],
    guideRef: "§6",
  },
  {
    slug: "importar-cronograma",
    title: "Importar cronograma desde presupuesto",
    summary: "Alineá el plan temporal a la EDT.",
    intents: ["cronograma"],
    modules: ["cronograma", "presupuesto"],
    level: "project",
    typicalRoles: ["PM"],
    where: { menu: "Planificación → Cronograma" },
    hrefs: [{ kind: "project", suffix: "/cronograma", label: "Cronograma" }],
    steps: [
      "Planificación → Cronograma → Importar desde presupuesto.",
      "Completá fechas en las hojas (no edites fechas de contenedores a mano: se pisan con el rollup).",
      "Agregá dependencias FS donde haga falta.",
    ],
    relatedSlugs: ["aprobar-el-presupuesto", "cargar-libro-de-obra", "cuatro-dimensiones-de-avance"],
    keywords: ["cronograma", "gantt", "importar", "fechas"],
    guideRef: "§7",
  },
  {
    slug: "cargar-libro-de-obra",
    title: "Cargar el parte de libro de obra",
    summary: "Avance real diario; al aprobar alimenta el cronograma.",
    intents: ["libro-obra"],
    modules: ["libro-obra"],
    level: "project",
    typicalRoles: ["Capataz", "PM"],
    where: { menu: "Operación → Libro de obra" },
    hrefs: [{ kind: "project", suffix: "/libro-obra", label: "Libro de obra" }],
    steps: [
      "Operación → Libro de obra → nuevo parte.",
      "Clima, cuadrilla, avance por partida EDT, fotos.",
      "Enviar (SUBMITTED): el PM del Equipo de obra (y OWNER/ADMIN) reciben campana + email.",
      "Si te lo devuelven, corregí desde el enlace de la notificación.",
    ],
    effects: [
      "Al aprobar: avance real del cronograma (+ consumo stock si aplica).",
      "Al aprobar/devolver: el autor recibe campana + email.",
    ],
    relatedSlugs: ["registrar-consumo-materiales", "asignar-equipo-de-obra", "usar-notificaciones"],
    keywords: ["libro de obra", "parte diario", "capataz", "avance", "parte pendiente"],
    guideRef: "§8",
  },
  {
    slug: "registrar-consumo-materiales",
    title: "Registrar consumo de materiales",
    summary: "Baja de stock imputada a partida cuando corresponde.",
    intents: ["consumo-materiales"],
    modules: ["materiales", "inventario"],
    level: "project",
    typicalRoles: ["Capataz", "PM", "Depósito"],
    where: { menu: "Operación → Consumos" },
    hrefs: [{ kind: "project", suffix: "/consumos", label: "Consumos" }],
    steps: [
      "Operación → Consumos (o el atajo Consumos en Materiales, o desde el flujo de libro de obra).",
      "Indicá material, cantidad y partida EDT si el parte toca varias partidas.",
    ],
    relatedSlugs: ["cargar-libro-de-obra", "pedir-material-desde-faltante", "tablero-materiales"],
    keywords: ["consumo", "consumos", "stock", "materiales"],
    guideRef: "§8",
  },
  {
    slug: "tablero-materiales",
    title: "Tablero de materiales",
    summary:
      "Cantidades APU vs pedido, recibido y consumido. Operativo y Varianza ($) en una fila; atajos a EDT, compras y consumos.",
    intents: ["pedir-material"],
    modules: ["materiales", "compras"],
    level: "project",
    typicalRoles: ["PM", "Compras", "Capataz"],
    where: { menu: "Operación → Materiales" },
    hrefs: [
      { kind: "project", suffix: "/materiales", label: "Materiales" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
      { kind: "project", suffix: "/control-costos", label: "EDT y costos" },
      { kind: "project", suffix: "/consumos", label: "Consumos" },
    ],
    steps: [
      "Operación → Materiales.",
      "En escritorio: a la izquierda Operativo / Varianza ($); a la derecha EDT y costos, Tablero de compras y Consumos (Exportar solo en Varianza).",
      "Operativo es cantidades (faltante → Pedir). Varianza ($) es desvío de $ vs consumo de stock.",
      "Para ver o crear solicitudes, entrá a Tablero de compras (Nueva solicitud / Todas las solicitudes). No hay atajo Solicitudes en Materiales.",
      "En celular o tablet chica: tarjetas de necesidad/faltante (sin Operativo/Varianza). Los mismos atajos quedan en una franja que se desplaza de costado; las etiquetas se acortan (EDT, Compras).",
    ],
    pitfalls: [
      "Materiales no reemplaza EDT y costos: acá son cantidades; el $ por partida está en Planificación → EDT y costos.",
    ],
    relatedSlugs: [
      "pedir-material-desde-faltante",
      "registrar-consumo-materiales",
      "circuito-comprar-material-hasta-pagarlo",
      "leer-edt-y-costos",
    ],
    keywords: [
      "tablero materiales",
      "materiales operativo",
      "varianza materiales",
      "atajos materiales",
    ],
    guideRef: "§9.0",
  },
];

export const PROCUREMENT_ARTICLES: HelpArticle[] = [
  {
    slug: "circuito-comprar-material-hasta-pagarlo",
    title: "Circuito: comprar material hasta pagarlo",
    summary:
      "SC/OC → confirmar (comprometido EDT) → recepción → factura → CxP → pago. El mapa completo de abastecimiento.",
    intents: ["comprar-material", "orden-compra", "pagar-cxp"],
    modules: ["compras", "materiales", "finanzas"],
    level: "project",
    typicalRoles: ["Compras", "PM", "Finanzas"],
    where: { menu: "Compras → Tablero de compras / OC / Facturas proveedor" },
    hrefs: [
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
      { kind: "project", suffix: "/cuentas-por-pagar", label: "Cuentas por pagar" },
    ],
    steps: [
      "1. Pedí desde Materiales (faltante) o creá la solicitud desde Tablero de compras / Solicitudes de compra, con partida EDT.",
      "2. Cotizá → seleccioná proveedor → OC en borrador (o OC directa si la política lo permite).",
      "3. Enviar → Aprobar → Confirmar al proveedor = Comprometido en EDT y costos.",
      "4. Registrar recepción (stock; no crea CxP sola).",
      "5. Registrar factura desde OC → Emitir = Devengado + CxP.",
      "6. Pagar la CxP (o Emitir y pagar ahora) = Pagado + egreso de caja.",
    ],
    effects: [
      "CONFIRMED OC → Comprometido",
      "Factura emitida → Devengado + CxP + asiento DRAFT",
      "Pago → Pagado + OUTFLOW",
    ],
    pitfalls: [
      "Subcontrato ≠ OC. Reintegro/gasto chico ≠ OC.",
      "Toda línea de obra imputa a partida hoja EDT.",
    ],
    relatedSlugs: [
      "pedir-material-desde-faltante",
      "tablero-materiales",
      "solicitud-de-compra",
      "orden-de-compra-y-afectar-edt",
      "recibir-una-oc",
      "factura-desde-oc",
      "pagar-una-cuenta-por-pagar",
    ],
    keywords: [
      "comprar material",
      "compra",
      "procure to pay",
      "orden de compra",
      "aprobar orden de compra",
      "afectar edt",
      "cuenta por pagar",
      "hierro",
      "cemento",
    ],
    guideRef: "§9 · §12.2 · §16",
  },
  {
    slug: "pedir-material-desde-faltante",
    title: "Pedir material desde faltante",
    summary: "Tablero de cantidades: Pedir prellena una solicitud de compra con el faltante restante.",
    intents: ["pedir-material", "comprar-material"],
    modules: ["materiales", "compras"],
    level: "project",
    typicalRoles: ["PM", "Compras"],
    where: { menu: "Operación → Materiales" },
    hrefs: [
      { kind: "project", suffix: "/materiales", label: "Materiales" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
    ],
    steps: [
      "Operación → Materiales (vista Operativo; en la misma fila, a la derecha, están los atajos).",
      "En una fila con faltante, pulsá Pedir. La cantidad prellenada es el resto (necesidad − ya pedido).",
      "Si ya hay una SC u OC de esa línea, el botón dice Pedir resto y también podés abrir el documento.",
      "Para el listado de solicitudes: atajo Tablero de compras → Todas las solicitudes / Nueva solicitud.",
    ],
    pitfalls: [
      "$ Presup. es el total APU de la línea, no el saldo por comprar.",
      "Pedido no incluye OC en borrador ni aprobada sin confirmar.",
    ],
    relatedSlugs: ["tablero-materiales", "solicitud-de-compra", "circuito-comprar-material-hasta-pagarlo"],
    keywords: ["pedir", "faltante", "materiales", "necesidad"],
    guideRef: "§9.0",
  },
  {
    slug: "solicitud-de-compra",
    title: "Solicitud de compra",
    summary: "Pedido interno con partida EDT, cotizaciones y selección de proveedor.",
    intents: ["solicitud-compra"],
    modules: ["compras"],
    level: "project",
    typicalRoles: ["PM", "Compras"],
    where: { menu: "Compras → Solicitudes de compra" },
    hrefs: [
      { kind: "project", suffix: "/solicitudes-compra", label: "Solicitudes de compra" },
      { kind: "project", suffix: "/compras", label: "Tablero de compras" },
    ],
    steps: [
      "Nueva solicitud desde Compras → Solicitudes de compra o Tablero de compras (Nueva solicitud / Todas las solicitudes). También desde Materiales → Pedir.",
      "Líneas con cantidad, unidad, descripción y partida EDT obligatoria.",
      "Guardar DRAFT → Enviar (SUBMITTED).",
      "Cargar cotizaciones (precio + plazo) según política.",
      "Seleccionar proveedor → genera OC en borrador.",
    ],
    relatedSlugs: ["tablero-materiales", "orden-de-compra-y-afectar-edt", "politicas-de-compras"],
    keywords: [
      "solicitud",
      "sc",
      "cotizacion",
      "pedido",
      "pedido de compra",
      "solicitud de compra",
    ],
    guideRef: "§9.1",
  },
  {
    slug: "orden-de-compra-y-afectar-edt",
    title: "Orden de compra y afectar EDT",
    summary: "Confirmar al proveedor = Comprometido en EDT y costos. No hay atajo Emitir y confirmar.",
    intents: ["orden-compra", "comprar-material"],
    modules: ["compras", "presupuesto"],
    level: "project",
    typicalRoles: ["Compras", "OWNER / ADMIN (aprobar)"],
    where: { menu: "Compras → Órdenes de compra" },
    hrefs: [{ kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" }],
    steps: [
      "Nueva OC o desde SC seleccionada. Cada línea: partida hoja + cantidades/precios.",
      "Enviar a aprobación → Aprobar (o Devolver a borrador con motivo).",
      "Confirmar al proveedor → CONFIRMED = Comprometido en EDT y costos.",
      "Luego recepción y factura.",
    ],
    effects: ["APPROVED = control interno; CONFIRMED = Comprometido."],
    pitfalls: ["Siempre Enviar → Aprobar → Confirmar; no existe atajo Emitir y confirmar."],
    relatedSlugs: [
      "circuito-comprar-material-hasta-pagarlo",
      "recibir-una-oc",
      "leer-edt-y-costos",
      "anular-devolver-cancelar-documentos",
      "afectaciones-comprometido-devengado-pagado",
    ],
    keywords: [
      "orden de compra",
      "oc",
      "aprobar orden de compra",
      "aprobar oc",
      "aprobacion oc",
      "enviar a aprobacion",
      "confirmar",
      "comprometido",
      "afectar edt",
    ],
    guideRef: "§9.2",
  },
  {
    slug: "recibir-una-oc",
    title: "Recibir una OC",
    summary: "Ingreso de stock. La recepción sola no crea cuenta por pagar.",
    intents: ["recepcion"],
    modules: ["compras", "inventario"],
    level: "project",
    typicalRoles: ["Compras", "Depósito"],
    where: { menu: "Compras → Recepciones" },
    hrefs: [
      { kind: "project", suffix: "/recepciones", label: "Recepciones" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
    ],
    steps: [
      "Desde la OC o Compras → Recepciones.",
      "Registrá recepción parcial o total.",
      "Después: Registrar factura desde OC para crear CxP.",
    ],
    effects: ["Stock + cantidades recibidas. No crea CxP sola."],
    relatedSlugs: ["factura-desde-oc", "orden-de-compra-y-afectar-edt"],
    keywords: [
      "recepcion",
      "recibir",
      "stock",
      "entrada",
      "remito",
      "ingresar mercaderia",
      "entrar mercaderia",
      "recibir oc",
    ],
    guideRef: "§9.2",
  },
  {
    slug: "factura-desde-oc",
    title: "Factura desde OC",
    summary: "Copia la partida EDT de cada línea. Al emitir: Devengado + CxP.",
    intents: ["factura-desde-oc"],
    modules: ["compras", "finanzas"],
    level: "project",
    typicalRoles: ["Compras", "Finanzas", "Administración"],
    where: { menu: "Facturas proveedor / desde OC" },
    hrefs: [
      { kind: "project", suffix: "/facturas-proveedor", label: "Facturas proveedor" },
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
    ],
    steps: [
      "Desde la OC: Registrar factura desde OC (Traer líneas).",
      "Revisá montos y adjunto del comprobante.",
      "Crear → borrador → Emitir (o Emitir y pagar ahora).",
    ],
    effects: ["Emitir → Devengado + CxP + asiento DRAFT."],
    relatedSlugs: ["pagar-una-cuenta-por-pagar", "emitir-y-pagar-ahora"],
    keywords: [
      "factura desde oc",
      "traer lineas",
      "factura proveedor",
      "factura de compra",
      "boleta",
      "boleta de compra",
    ],
    guideRef: "§9.2 · §12.2",
  },
  {
    slug: "oc-directa-vs-con-solicitud",
    title: "OC directa vs con solicitud",
    summary: "OC directa solo si la política de compras lo habilita.",
    intents: ["oc-directa", "orden-compra"],
    modules: ["compras", "configuracion"],
    level: "project",
    typicalRoles: ["Compras", "OWNER / ADMIN"],
    where: { menu: "Compras → Órdenes de compra / Configuración → Políticas" },
    hrefs: [
      { kind: "project", suffix: "/ordenes-compra", label: "Órdenes de compra" },
      { kind: "company", path: "/configuracion/politicas", label: "Políticas" },
    ],
    steps: [
      "Con SC: flujo completo de cotización y selección.",
      "OC directa: Nueva OC sin SC si la política lo permite; umbrales altos pueden exigir motivo de emergencia.",
    ],
    relatedSlugs: ["politicas-de-compras", "orden-de-compra-y-afectar-edt"],
    keywords: ["oc directa", "sin solicitud", "emergencia"],
    guideRef: "§9.2",
  },
];
