import type { HelpArticle } from "../types";

export const SETUP_ARTICLES: HelpArticle[] = [
  {
    slug: "crear-y-activar-una-obra",
    title: "Crear y activar una obra",
    summary: "Alta de proyecto con cliente del Directorio y activación a ACTIVE.",
    intents: ["crear-obra"],
    modules: ["proyectos"],
    level: "company",
    typicalRoles: ["OWNER / ADMIN", "PM"],
    permissionHint: "Necesitás permiso para crear proyectos.",
    where: { menu: "General → Proyectos → Nuevo proyecto" },
    hrefs: [
      { kind: "company", path: "/proyectos/nuevo", label: "Nuevo proyecto" },
      { kind: "company", path: "/proyectos", label: "Listado de proyectos" },
    ],
    steps: [
      "Prerrequisito: contacto con rol Cliente activo en Directorio.",
      "Proyectos → Nuevo proyecto: código, tipo (Privado/Público), nombre, cliente.",
      "Crear proyecto → estado DRAFT.",
      "En el resumen, Activar obra → ACTIVE.",
    ],
    effects: ["Sin activar, la operación diaria queda limitada."],
    relatedSlugs: ["cargar-un-cliente", "armar-presupuesto-edt-apu"],
    keywords: ["crear proyecto", "crear obra", "activar obra", "nuevo proyecto"],
    guideRef: "§5.1",
  },
  {
    slug: "invitar-un-usuario",
    title: "Invitar un usuario y asignar roles",
    summary: "Alta de miembros del equipo con email de invitación.",
    intents: ["invitar-usuario", "roles-permisos"],
    modules: ["configuracion"],
    level: "company",
    typicalRoles: ["OWNER", "ADMIN"],
    permissionHint: "Solo OWNER/ADMIN gestionan el equipo.",
    where: { menu: "Configuración → Equipo → Invitar" },
    hrefs: [
      { kind: "company", path: "/configuracion/equipo/invitar", label: "Invitar usuario" },
      { kind: "company", path: "/configuracion/equipo", label: "Equipo" },
    ],
    steps: [
      "Configuración → Equipo → Invitar.",
      "Indicá email y roles.",
      "El invitado acepta en /invitaciones/aceptar (sin pegar el token a mano).",
      "Ajustá roles después en el detalle del miembro si hace falta.",
    ],
    relatedSlugs: ["que-ve-cada-rol"],
    keywords: ["invitar", "usuario", "equipo", "roles", "permisos"],
    guideRef: "§2.1",
  },
  {
    slug: "que-ve-cada-rol",
    title: "Qué ve cada rol (empresa vs obra)",
    summary:
      "Finanzas / Tesorería / Contabilidad de empresa solo para roles de company finance (D-056). El resto opera desde la obra.",
    intents: ["roles-permisos"],
    modules: ["configuracion", "finanzas", "general"],
    level: "both",
    typicalRoles: ["OWNER", "ADMIN"],
    where: { menu: "Configuración → Permisos / Equipo" },
    hrefs: [
      { kind: "company", path: "/configuracion/permisos", label: "Permisos" },
      { kind: "company", path: "/configuracion/equipo", label: "Equipo" },
    ],
    steps: [
      "Company finance (OWNER, ADMIN, FINANCE, TREASURER, VIEWER lectura): ven hub /finanzas, /tesoreria, /contabilidad.",
      "PM, Compras, PROJECT_FINANCE, SALES: finanzas desde /proyectos/[id]/…, no el hub corporativo.",
      "No des company finance a un PM «para ver más».",
    ],
    pitfalls: ["Dar company finance a PM/Compras expone caja y GL de toda la empresa."],
    relatedSlugs: ["invitar-un-usuario"],
    keywords: ["roles", "que ve", "permisos", "company finance", "d-056"],
    guideRef: "§1.2 · D-056",
  },
  {
    slug: "politicas-de-compras",
    title: "Políticas de compras",
    summary: "Umbral de aprobación OC, SC requerida, cotizaciones, OC directa y desvíos.",
    intents: ["politicas-compras"],
    modules: ["configuracion", "compras"],
    level: "company",
    typicalRoles: ["OWNER", "ADMIN"],
    permissionHint: "Configuración de políticas: OWNER/ADMIN.",
    where: { menu: "Configuración → Políticas" },
    hrefs: [{ kind: "company", path: "/configuracion/politicas", label: "Políticas" }],
    steps: [
      "Abrí Configuración → Políticas.",
      "Revisá umbral de aprobación, SC requerida, min/max cotizaciones, OC directa, auto-aprobación, emergencia y % de desvíos.",
      "Guardá. Las OC nuevas respetan esas reglas.",
    ],
    relatedSlugs: ["orden-de-compra-y-afectar-edt", "oc-directa-vs-con-solicitud"],
    keywords: ["politicas", "compras", "umbral", "cotizaciones", "oc directa"],
    guideRef: "§1.3 · §9",
  },
];

export const TREASURY_ARTICLES: HelpArticle[] = [
  {
    slug: "crear-cuenta-tesoreria",
    title: "Crear una cuenta de caja o banco",
    summary: "Configurá tesorería antes de cobrar y pagar.",
    intents: ["cuenta-tesoreria"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["OWNER / ADMIN", "Finanzas", "Tesorería"],
    permissionHint: "Necesitás ver Cuentas de tesorería (company finance).",
    where: { menu: "Tesorería → Cuentas → Nueva" },
    hrefs: [
      { kind: "company", path: "/tesoreria/cuentas/nueva", label: "Nueva cuenta" },
      { kind: "company", path: "/tesoreria/cuentas", label: "Listado de cuentas" },
    ],
    steps: [
      "Tesorería → Cuentas → Nueva (o + Nueva cuenta).",
      "Indicá tipo (banco/caja/billetera), moneda y saldo de apertura si aplica.",
      "Usá esa cuenta al cobrar (INFLOW) o pagar (OUTFLOW).",
    ],
    relatedSlugs: ["transferir-entre-cuentas", "ver-movimientos-de-tesoreria", "por-que-un-pago-se-bloquea"],
    keywords: ["caja", "banco", "cuenta tesoreria", "saldo apertura", "nueva cuenta", "caja chica"],
    guideRef: "§4",
  },
  {
    slug: "transferir-entre-cuentas",
    title: "Transferir entre cuentas propias",
    summary: "Dos movimientos atómicos (salida + entrada) entre cuentas del tenant.",
    intents: ["transferencia"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["Tesorería", "Finanzas"],
    where: { menu: "Tesorería → Transferencias" },
    hrefs: [{ kind: "company", path: "/tesoreria/transferencias", label: "Transferencias" }],
    steps: [
      "Tesorería → Transferencias.",
      "Elegí cuenta origen, destino, monto y fecha.",
      "Confirmá. No puede dejar la origen en negativo.",
    ],
    relatedSlugs: ["crear-cuenta-tesoreria", "ver-movimientos-de-tesoreria"],
    keywords: ["transferencia", "entre cuentas", "mover plata", "transferir plata", "guita"],
    guideRef: "§4",
  },
  {
    slug: "ver-flujo-de-caja",
    title: "Ver el flujo de caja",
    summary: "Ingresos y egresos por período (sin mezclar transferencias internas en el neto operativo).",
    intents: ["flujo-caja"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["Tesorería", "Finanzas", "OWNER / ADMIN"],
    permissionHint: "Rol de company finance + módulo Tesorería.",
    where: { menu: "Tesorería → Flujo de caja" },
    hrefs: [{ kind: "company", path: "/tesoreria/flujo-caja", label: "Flujo de caja" }],
    steps: [
      "Tesorería → Flujo de caja.",
      "Elegí el período y revisá ingresos vs egresos.",
      "Para el detalle línea a línea usá Movimientos.",
    ],
    relatedSlugs: ["ver-movimientos-de-tesoreria", "crear-cuenta-tesoreria"],
    keywords: ["flujo de caja", "cashflow", "ingresos", "egresos", "tesoreria"],
    guideRef: "§4.0",
  },
  {
    slug: "ver-movimientos-de-tesoreria",
    title: "Ver movimientos de tesorería",
    summary: "Ledger / extracto interno: confirmados y conciliados.",
    intents: ["movimientos-tesoreria"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["Tesorería", "Finanzas"],
    where: { menu: "Tesorería → Movimientos" },
    hrefs: [{ kind: "company", path: "/tesoreria/movimientos", label: "Movimientos" }],
    steps: [
      "Tesorería → Movimientos.",
      "Filtrá por cuenta, fecha, tipo (Ingreso / Egreso / Ajuste).",
      "Revisá la columna Estado: Confirmado vs Conciliado.",
      "Los movimientos operativos nacen al cobrar y pagar; no se borran, se anulan con traza.",
    ],
    relatedSlugs: ["ver-flujo-de-caja", "conciliar-el-banco", "por-que-un-pago-se-bloquea"],
    keywords: ["movimientos", "ledger", "extracto", "confirmado", "conciliado"],
    guideRef: "§4.0",
  },
  {
    slug: "conciliar-el-banco",
    title: "Conciliar el banco",
    summary: "Emparejar extracto bancario vs movimientos del sistema y cerrar la sesión.",
    intents: ["conciliacion"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["Tesorería", "Finanzas", "ADMIN"],
    where: { menu: "Tesorería → Conciliación" },
    hrefs: [{ kind: "company", path: "/tesoreria/conciliacion", label: "Conciliación" }],
    steps: [
      "Tesorería → Conciliación → Nueva.",
      "Importá CSV/OFX o cargá líneas del extracto.",
      "Emparejá movimientos del sistema con el extracto.",
      "Cerrar conciliación cuando el mes cuadre.",
    ],
    pitfalls: [
      "No canceles un pago/cobranza si el movimiento ya está Conciliado: desemparejá primero.",
    ],
    relatedSlugs: ["ajuste-manual-de-caja", "cerrar-el-mes", "ver-movimientos-de-tesoreria"],
    keywords: ["conciliacion", "extracto", "ofx", "banco"],
    guideRef: "§4.2",
  },
  {
    slug: "ajuste-manual-de-caja",
    title: "Ajuste manual de caja",
    summary: "Corrección de saldo con motivo documentado (no reemplaza cobros/pagos).",
    intents: ["ajuste-caja"],
    modules: ["tesoreria"],
    level: "company",
    typicalRoles: ["Tesorería", "ADMIN"],
    where: { menu: "Tesorería → Cuentas → detalle → Ajuste manual" },
    hrefs: [{ kind: "company", path: "/tesoreria/cuentas", label: "Cuentas" }],
    steps: [
      "Abrí el detalle de la cuenta.",
      "CTA Ajuste manual: monto, fecha y motivo.",
      "Confirmá. Queda movimiento ADJUSTMENT.",
    ],
    relatedSlugs: ["conciliar-el-banco", "ver-movimientos-de-tesoreria"],
    keywords: ["ajuste", "ajuste manual", "corregir saldo", "caja chica"],
    guideRef: "§4.3",
  },
  {
    slug: "por-que-un-pago-se-bloquea",
    title: "Por qué un pago se bloquea",
    summary: "Fondos insuficientes, período cerrado o movimiento conciliado.",
    intents: ["pago-bloqueado", "pagar-cxp"],
    modules: ["tesoreria", "finanzas", "contabilidad"],
    level: "both",
    typicalRoles: ["Finanzas", "Tesorería"],
    where: { menu: "CxP → Pagar / Transacciones" },
    hrefs: [
      { kind: "company", path: "/finanzas/cuentas-por-pagar", label: "Cuentas por pagar" },
      { kind: "company", path: "/tesoreria/cuentas", label: "Cuentas de tesorería" },
    ],
    steps: [
      "Fondos: el pago no puede dejar la cuenta en negativo — revisá saldo.",
      "Período cerrado: usá fecha de un mes abierto o pedí Reabrir (OWNER/ADMIN + motivo).",
      "Movimiento conciliado: desemparejá / reabrí la conciliación antes de cancelar.",
    ],
    relatedSlugs: ["pagar-una-cuenta-por-pagar", "cerrar-el-mes", "conciliar-el-banco"],
    keywords: [
      "pago bloqueado",
      "fondos insuficientes",
      "period closed",
      "no puedo pagar",
      "no me deja pagar",
      "bloqueado",
    ],
    guideRef: "§4 · §12.2 · §17",
  },
];
